### ISSUE TITLE
Which system benchmark should we choose?

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#1016]
Recently, I find there are several proposals about system benchmarks, e.g., #1003 and #889 , which seem to have similar tests and make me confused. So I did a simple research about them.

### Overview

**To begin with, I think that `lmbench` is the most suitable tool for performance monitoring during the development of Asterinas. (lmbench > unixbench > sysbench)**

- If you need to evaluate the performance of database servers, especially in OLTP (Online Transaction Processing) scenarios, `sysbench` is the optimal choice. 
- For assessing the overall performance and stability of an operating system, `unixbench` is a good option. 
- If you require system tuning and performance analysis, particularly focusing on low-level performance metrics, `lmbench` is the best choice.

Below is a more detailed introduction to `sysbench`, `unixbench`, and `lmbench`, including their main functionalities, test items, and reference links:

### sysbench

**Detailed Introduction**:
`sysbench` is a modular, cross-platform, multi-threaded benchmarking tool primarily used to evaluate database loads under different system parameters. It tests various aspects of the system, such as CPU, memory, file I/O, threading, and database performance. The design goal of `sysbench` is to provide a simple, extensible framework for conducting various system-level performance tests.

**Main Functionalities**:
- **CPU Performance Testing**: Evaluates CPU computational capabilities, such as prime number calculations.
- **Memory Access Performance Testing**: Measures the read and write speeds of memory.
- **File I/O Performance Testing**: Assesses the read and write performance of the file system.
- **Threading Performance Testing**: Evaluates the scheduling performance of multi-threading.
- **Mutex Performance Testing**: Measures the performance of mutex locks.
- **Database Performance Testing**: Tests the performance of databases like MySQL and PostgreSQL.

**Reference Links**:
- [sysbench Official Documentation](https://github.com/akopytov/sysbench/blob/master/README.md)

### unixbench

**Detailed Introduction**:
`unixbench` is a benchmarking tool designed to evaluate the overall performance of UNIX systems. It includes multiple test items covering CPU, memory, file I/O, process creation and termination, 2D and 3D graphics performance, and more. The goal of `unixbench` is to provide a comprehensive performance evaluation to help users understand the overall performance and stability of their systems.

**Main Functionalities**:
- **System Call Overhead**: Measures the overhead of system calls.
- **Process Creation and Termination Time**: Evaluates the time taken to create and terminate processes.
- **File Read and Write Performance**: Assesses the read and write performance of the file system.
- **Pipe Throughput**: Measures the throughput of pipes.
- **Memory Operation Performance**: Evaluates the read and write performance of memory.
- **2D and 3D Graphics Performance**: Tests graphics performance.

**Main Test Items**:
- Dhrystone: Tests CPU performance.
- Whetstone: Tests floating-point operation performance.
- File Copy: Evaluates file read and write performance.
- Pipe Throughput: Measures pipe throughput.
- Pipe-based Context Switching: Tests context switching performance based on pipes.
- Process Creation: Measures process creation time.
- System Call Overhead: Evaluates system call overhead.
- Shell Scripts: Tests the execution performance of shell scripts.

**Reference Links**:
- [unixbench Official Documentation](https://github.com/kdlucas/byte-unixbench/blob/master/README.md)

### lmbench

**Detailed Introduction**:
`lmbench` is a benchmarking tool designed to evaluate low-level performance metrics of systems. It focuses on measuring system latency and bandwidth, including memory access latency, process creation time, context switching time, file system read and write latency, and more. The goal of `lmbench` is to provide detailed performance data to help users with system tuning and performance analysis.

**Main Functionalities**:
- **Memory Access Latency**: Measures the latency of memory access.
- **Memory Bandwidth**: Evaluates the bandwidth of memory.
- **Process Creation Time**: Measures the time taken to create processes.
- **Context Switching Time**: Evaluates the time taken for context switching.
- **File System Read and Write Latency**: Assesses the read and write latency of the file system.
- **Network Bandwidth and Latency**: Tests network bandwidth and latency.

**Main Test Items**:
- **Latency**: Measures the latency of various operations, such as memory access, context switching, and process creation.
- **Bandwidth**: Evaluates the bandwidth of various operations, such as memory copying and file read and write.
- **Throughput**: Measures the throughput of various operations, such as network transmission.

**Reference Links**:
- [lmbench GitHub Repository](https://github.com/intel/lmbench)

### Summary

- **`sysbench`**: Suitable for performance testing of databases and basic system components.
- **`unixbench`**: Suitable for evaluating the overall performance of UNIX systems.
- **`lmbench`**: Suitable for evaluating low-level performance metrics of systems.

**Comment by tatetian** [comment]
So I think our strategy should be choosing lmbench as the primary benchmark suite while selecting some benchmarks (e.g., thread, mutex, and pipe) from sysbench and unixbench to complement lmbench.
