### ISSUE TITLE
MMIO access generates unexpected instruction

### ISSUE THREAD

**Issue by Hsy-Intel** [asterinas/asterinas#1052]
### Describe the bug

The [two lines in MMIO init file](https://github.com/asterinas/asterinas/blob/main/ostd/src/bus/mmio/mod.rs#L62-L63):

```rust
let value = unsafe { *(paddr_to_vaddr(current) as *const u32) };
if value == VIRTIO_MMIO_MAGIC {
```
will generate a `Cmp_rm32_imm32` instruction if we set `RELEASE=1`.

However, we expect to access the MMIO region using only read or write instructions. Only these cases are handled in TDX MMIO emulation.

Therefore, we need to prevent the compiler from generating similar instructions when accessing MMIO. (Currently only found this one)

**Comment by sdww0** [comment]
Maybe we can use `Volatile<&' static u32, ReadOnly>` or `core::ptr::read_volatile` to read the magic value. I think it will fix the problem. Can you try the following code and see whether the issue will fixed?

```rust
let magic = Volatile::new_read_only(unsafe { &*(paddr_to_vaddr(current) as *const u32) });
if magic.read() == VIRTIO_MMIO_MAGIC {
```

or

```rust
let magic = unsafe { core::ptr::read_volatile(paddr_to_vaddr(current) as *const u32) };
if magic == VIRTIO_MMIO_MAGIC {
```

**Comment by Hsy-Intel** [comment]
> Maybe we can use `Volatile<&' static u32, ReadOnly>` or `core::ptr::read_volatile` to read the magic value. I think it will fix the problem. Could you please try running the following code to see if it fixes the issue?
> 
> ```rust
> let magic = Volatile::new_read_only(unsafe { &*(paddr_to_vaddr(current) as *const u32) });
> if magic.read() == VIRTIO_MMIO_MAGIC {
> ```
> 
> or
> 
> ```rust
> let magic = unsafe { core::ptr::read_volatile(paddr_to_vaddr(current) as *const u32) };
> if magic == VIRTIO_MMIO_MAGIC {
> ```

Both work fine, thanks!
