### ISSUE TITLE
CPU local memory is used before initialized

### ISSUE THREAD

**Issue by YanWQ-monad** [asterinas/asterinas#1069]
The use (in `ostd`):
`init` → `mm::heap_allocator::init` → `HEAP_ALLOCATOR.init` → `SpinLock::lock_irq_disabled` → `trap::irq::disable_local` → `task::processor::disable_preempt` → `PREEMPT_COUNT.increase_num_locks`, where `PREEMPT_COUNT` is a cpu-local variable.

The initialization:
`init` → `cpu::cpu_local::init_on_bsp` → ...

The use is before the initialization since `mm::heap_allocator::init` is called prior to `cpu::cpu_local::init_on_bsp`.
https://github.com/asterinas/asterinas/blob/94eba6d85eb9e62ddd904c1132d556b808cc3174/ostd/src/lib.rs#L51-L82

---

It does not fault in x86 because `fsbase` is by default `0`, and the OS has write access to the memory near `0x0`, so the error is silent. But in RISC-V, this memory region is not writable, so it faults.

And I guess this is not the only case since `SpinLock` is widely used in `ostd`, it might be other uses of `SpinLock` before CPU local memory is initialized, for example, `mm::kspace::init_boot_page_table` → `BOOT_PAGE_TABLE.lock`.

**Comment by YanWQ-monad** [comment]
Modifying `ostd::arch::x86::cpu::get_cpu_local_base` to
``` rust
/// Gets the base address for the CPU local storage by reading the FS base model-specific register.
pub(crate) fn get_cpu_local_base() -> u64 {
    let fsbase = FS::read_base().as_u64();
    debug_assert_ne!(fsbase, 0, "CPU local memory is used before initialized");
    fsbase
}
```
may help with discovering cpu local used before initialization bugs.

**Comment by junyang-zh** [comment]
> And I guess this is not the only case since SpinLock is widely used in ostd, it might be other uses of SpinLock before CPU local memory is initialized, for example, mm::kspace::init_boot_page_table → BOOT_PAGE_TABLE.lock.

Indeed. CPU local variables should not be accessed before initialization of `mod cpu_local`. I will look into it.
