### ISSUE TITLE
Typo: A typo when assigning 'dst.rbx' at `copy_gp_regs`.

### ISSUE THREAD

**Issue by CherishCai** [asterinas/asterinas#1078]
Here was changed 3 days ago. Is there a typo when assigning 'dst.rbx' at `copy_gp_regs`?
﻿
https://github.com/asterinas/asterinas/blob/20524ae64a3472a5381e7e5aa960a124d050e57b/kernel/aster-nix/src/arch/x86/cpu.rs#L72

**Comment by junyang-zh** [comment]
I see it as a bug indeed. It may have led to haunting random failures. Could you please open up a PR to fix it? Thanks very much for spotting it anyway!
