### ISSUE TITLE
Lockless mutability for current task data.

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#1106]
**This is currently a work-in-progress RFC**

### Summary

This RFC plans to introduce a mechanism for implementing lock-less inner mutability of task data that would be only accessible through the current task.

### Context and Problem Statement

In `aster-nix`, there would be a hell lot of inner mutability patterns using `Mutex` or `SpinLock` in the thread structures, such as `SigMask`, `SigStack` and `sig_context`, etc. They are all implemented with locks. However, they should only be accessed through the current thread. There would be no syncing required. Modifying them from non-current threads should be illegal. Locks are too heavy-weighted for such kind of inner mutability patterns.

Also, for shared thread/task data, we access them using `current!` in thread/task contexts. These operations would also require fetching the task from a `cpu_local!` object that incurs heavy type-checking and interrupt/preempt blocking operations. Such jobs can be ignored when the caller is definitely in the current task's contexts. As #1105 points out, even the most simple system call `getpid` would access such task exclusive variables many times. Current implementation would require multiple locking operations and IRQ/preempt guarding operations. Many cycles are wasted doing so.

We currently only have per-task data storage that is shared (the implementer should provide `Send + Sync` types). Most of the data that don't need to be shared are also stored here, which would require a lock for inner mutability. In this RFC, I would like to introduce a new kind of data in the `ostd::Task` that is exclusive (not shared, no need to be `Send + Sync`). It would offer a chance to implement the above mentioned per-task storage without locks, boosting the performance by a lot.

### Proposal

Currently we access them via `current!()`, which would return a reference over the current task and it's corresponding data. The data is defined within a structure (either `PosixThread` or `KernelThread` currently).

In `aster-nix`, most code are running in the context of a task (other code runs in interrupt contexts). So the code would only have one replica of task local exclusive data that is accessible. Such data would only be accessed by the code in the corresponding task context also. Such kind of data should be safely mutably accessed. OSTD should provide a way to define task-context-global per-task mutable variables that are not visible in interrupt contexts. By doing so, many of the data specific to a task can be implemented lock-less.

#### Task entry point

The optimal solution would let the task function receive references to the task data as arguments. Then all the functions that requires the data of the current task would like to receive arguments like so. This is the requirement of a function that should be used as a task entry point:

```rust
/// The entrypoint function of a task takes 4 arguments:
///  1. the mutable task context,
///  2. the shared task context,
///  3. the reference to the mutable per-task data,
///  4. and the reference to the per-task data.
pub trait TaskFn =
    Fn(&mut MutTaskInfo, &SharedTaskInfo, &mut dyn Any, &(dyn Any + Send + Sync)) + 'static;
```

An example of usage:

```rust
// In `aster-nix`

use ostd::task::{MutTaskInfo, Priority, SharedTaskInfo};
use crate::thread::{
    MutKernelThreadInfo, MutThreadInfo, SharedKernelThreadInfo, SharedThreadInfo, ThreadExt,
};

fn init_thread(
    task_ctx_mut: &mut MutTaskInfo,
    task_ctx: &SharedTaskInfo,
    thread_ctx_mut: &mut MutThreadInfo,
    thread_ctx: &SharedThreadInfo,
    kthread_ctx_mut: &mut MutKernelThreadInfo,
    kthread_ctx: &SharedKernelThreadInfo,
) {
    println!(
        "[kernel] Spawn init thread, tid = {}",
        thread_ctx.tid
    );
    let initproc = Process::spawn_user_process(
        karg.get_initproc_path().unwrap(),
        karg.get_initproc_argv().to_vec(),
        karg.get_initproc_envp().to_vec(),
    )
    .expect("Run init process failed.");
    // Wait till initproc become zombie.
    while !initproc.is_zombie() {
        // We don't have preemptive scheduler now.
        // The long running init thread should yield its own execution to allow other tasks to go on.
        task_ctx_mut.yield_now();
    }
}

#[controlled]
pub fn run_first_process() -> ! {
    let _thread = thread::new_kernel(init_thread, Priority::normal(), CpuSet::new_full());
}
```

Such approach can eliminate the need of neither `current!` nor `current_thread!`, but introduces verbose parameters for the functions. This approach would be implemented by #1108 .

#### Context markers

Of course, the easiest way to block IRQ code from accessing task exclusive local data is to have a global state `IN_INTERRUPT_CONTEXT` and check for this state every time when accessing the task exclusive local variables. This would incur some (but not much) runtime overhead. Such overhead can be eliminated by static analysis, which we would encourage.

There would be 3 kind of contexts: the bootstrap context, the task context and the interrupt context. So the code would have $2^3=8$ types of possibilities to run in different contexts. But there are only 4 types that are significant:

 1. Utility code that could run in all 3 kind of contexts;
 2. Bootstrap code that only runs in the bootstrap context;
 3. The IRQ handler that would only run in the interrupt context;
 4. Task code that would only run in the task context.

Other code can be regarded as the type 1., since we do not know where would it run (for example, the page table cursor methods).

Code must be written in functions (except for some really low level bootstrap code, which are all in OSTD). So we can mark functions with the above types, and check if type 1./2./3. functions accessed task local exclusive global variables.

Here are the rules for function types:

 - All functions that may call 2. should be 2., the root of type 2. function is `ostd::main` and `ostd::ap_entry`;
 - all functions that may call 3. should be 3., the root of type 3. functions are send to `IrqLine::on_active`;
 - all functions that may call 4. should be 4., the root of type 4. functions are send to `TaskOptions`;
 - if a function can be call with multiple types of functions, it is type 1.

In this alternative, two tools will be introduced:

 1. A procedural macro crate `code_context` (re-exported by OSTD) that provides function attributes `#[code_context::task]`, `#[code_context::interrupt]`, `#[code_context::boot]`. If not specified, the function is type 1.;
 2. A tools that uses rustc to check the above rules ([an example](https://github.com/heinzelotto/rust-callgraph/tree/master)). OSDK would run this tool before compilation to reject unsound code.

**Comment by tatetian** [comment]
Let's say we have a function `foo` with `#[code_context::task]` attribute. How would this `foo` function "receive references to the task data as arguments"? What would the user code look like?

**Comment by lrh2000** [comment]
> ```rust
> /// The entrypoint function of a task takes 4 arguments:
> ///  1. the mutable task context,
> ///  2. the shared task context,
> ///  3. the reference to the mutable per-task data,
> ///  4. and the reference to the per-task data.
> pub trait TaskFn =
>     Fn(&mut MutTaskInfo, &SharedTaskInfo, &mut dyn Any, &(dyn Any + Send + Sync)) + 'static;
> ```

Could you please change it to `FnOnce`?

https://github.com/asterinas/asterinas/blob/20a856b07fa8210fdd2d46d3feb5087004c27afb/kernel/aster-nix/src/fs/pipe.rs#L233-L235
