### ISSUE TITLE
Improve the ergonomics when using spinlocks with IRQ disabled

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#1117]
This issue proposes to refactor the API of `SpinLock` to improve the ergonomics when using spinlocks with IRQ disabled。

### Current Feature

In many situations, `SpinLock` must be acquired with IRQ disabled to prevent deadlock. Here is an example.

```rust
impl Scheduler for PreemptScheduler {
    fn enqueue(&self, task: Arc<Task>) {
        if task.is_real_time() {
            self.real_time_tasks.lock_irq_disabled().push_back(task);
        } else {
            self.normal_tasks.lock_irq_disabled().push_back(task);
        }
    }
}
```

There are two problems with the current API of `SpinLock`.

First, the API is unscalable. The lock operation has several forms:
* The basic version (`lock`)
* The try version (`try_lock`)
* The owned version (`lock_arc`)

Theoretically, each one of them may need an IRQ disabled variant. Currently, we only have `lock_irq_disabled`, but we could have `try_lock_irq_disabled` and `lock_arc_irq_disabled` in the future. 

Furthermore, we may decide to add yet another variant that disables soft IRQs. We may need to have `lock_softirq_disabled`, `try_lock_softirq_disabled`, and `lock_arc_softirq_disabled`. Surely, you would agree that such an API design looks ugly.

Second, a developer may mistakenly use `lock`, instead of `lock_irq_disabled`, when a lock should be always acquired with IRQ disabled. In this case, if our API can make `lock` mean `lock_irq_disabled`, then the developer will not make such mistakes.

### Enhancement Description

I propose to improve the API for `SpinLock` using a chained call technique.

```rust
fn test_lock(lock: Arc<SpinLock<u32>>) {
    let _ = lock.lock();
    let _ = lock.try_lock();
    let _ = lock.lock_arc();

    let _ = lock.disable_irq().lock();
    let _ = lock.disable_irq().try_lock();
    let _ = lock.disable_irq().lock_arc();

    let _ = lock.disable_softirq().lock();
    let _ = lock.disable_softirq().try_lock();
    let _ = lock.disable_softirq().lock_arc();
}
```

And if the lock should be always acquired with IRQ disabled, she can convey this intention by specifying the second type type parameter of `SpinLock` with `IrqDisabled`.

```rust
fn test_lock(lock: Arc<SpinLock<u32, IrqDisabled>>) {
    // The IRQ are always disabled. No need to call `disable_irq` method.
    // In fact, this method does not exist on `SpinLock<_, IrqDisabled>`.
    let _ = lock.lock();
    let _ = lock.try_lock();
    let _ = lock.lock_arc();
}
```

### Motivation

The new API is elegant on supporting various forms of the lock operation and less error prone when a lock should always be used with IRQ disabled.

### Draft Implementation

Here is how the proposed API may be implemented. Only key modifications are shown.

First, the `SpinLock` will have one more generic type parameter `G`, whose default type is `PreemptDisabled`, indicating that acquiring this lock disables preemption.

```rust
#[repr(C)]
pub struct SpinLock<T: ?Sized, G = PreemptDisabled> {
    lock: AtomicBool,
    val: UnsafeCell<T>,
    phantom: PhantomData<G>,     
}
```

Also note that the layout is specified as `repr(C)`. The reason will be evident later.

The type `G` must implement the `Guardian` trait.

```rust
/// A guardian type returns a guard object.
pub trait Guardian {
    type Guard;

    /// Returns a guard object.
    fn guard() -> Self::Guard;
}
```

There are two guardian types. The first one, `PreemptDisabled`, can be used by `SpinLock` to construct `DisablePreemptGuard`.

```rust
pub struct PreemptDisabled;

impl Guardian for PreemptDisabled {
    type Guard = DisablePreemptGuard;

    fn guard() -> Self::Guard {
        disable_preempt()
    }
}
```

The second one is `LocalIrqDisabled`

```rust
pub struct LocalIrqDisabled;

impl Guardian for IrqDisabled {
    type Guard = DisabledLocalIrqGuard

    fn disable() -> Self::Guard {
        disable_irq()
    }
}
```

The old `lock_irq_disabled` method is replaced with a new `disable_irq` method.

```rust
impl<T> SpinLock<T, PreemptDisabled> {
    pub fn disable_irq(&self) -> &Self<T, LocalIrqDisabled> {
        // SAFETY: The memory layout of the source and target types, which only differ in the `phantom` field, are identical because
        // (1) `PhantomData` is zero-sized, (2) the struct layout follows `repr(C)`.
        unsafe {
            core::mem::transmute(self)
        }
    }
}
```

Regardless of the specific guardian type, the lock methods can be implemented the same way.

```rust
impl<T, G: Guardian> SpinLock<T, G> {
    pub fn lock(&self) -> SpinLockGuard<T, G::Guard> {
        let inner_guard = G::guard();
        self.acquire_lock();
        SpinLockGuard_ {
            lock: self,
            inner_guard,
        }
    }

    pub fn lock_arc(self: &Arc<Self>) -> ArcSpinLockGuard<T, G::Guard> {
        let inner_guard = G::guard();
        self.acquire_lock();
        SpinLockGuard_ {
            lock: self.clone(),
            inner_guard,
        }
    }
}
```

### Alternatives

I checked the [SpinLock in Rust for Linux](https://github.com/Rust-for-Linux/linux/blob/rust-next/rust/kernel/sync/lock.rs). It does not provide any API to support locking with IRQ disabled. So we are alone in this problem space.

**Comment by lrh2000** [comment]
I'm not sure there is an elegant way to avoid `transmute`. But _if_ we finally decide to use it, how about using `repr(transparent)` instead of `repr(C)`?
```rust
struct SpinLockInner<T: ?Sized> {
    lock: AtomicBool,
    val: UnsafeCell<T>,
}

#[repr(transparent)]
pub struct SpinLock<T: ?Sized, G> {
    phantom: PhantomData<G>,
    inner: SpinLockInner<T>,
}
```

According to [the documentation](https://doc.rust-lang.org/nomicon/other-reprs.html):
```
#[repr(transparent)] can only be used on a struct or single-variant enum that has a single non-zero-sized field (there may be additional zero-sized fields). 

[..]

The goal is to make it possible to transmute between the single field and the struct/enum.
```

So it is safe to transmute between `&SpinLock<T, GuardA>`, `&SpinLockInner<T>`, and `&SpinLock<T, GuardB>`. I think this is more "rusty" than `repr(C)`. The only overhead is that we have to have an inner type, but I think that's negligible.

See also [bytemuck::TransparentWrapper](https://docs.rs/bytemuck/latest/bytemuck/trait.TransparentWrapper.html).
