### ISSUE TITLE
Schedule task periodically

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#1131]
I'm not sure if this is a feature request or a bug, but I'm certain that it is a problem. Therefore, I'm creating a blank issue instead. Here is the problem I discovered:

## Problem

The `lat_unix_connect` in LMbench will result in a connection refused error when running in Asterinas with `LOG_LEVEL=error`. However, it works well with `LOG_LEVEL=debug`. Then I found that the problem was that the server process failed to call the 'accept' syscall in time, causing the size of 'incoming_endpoints' in 'Backlog' to reach the 'backlog'.

## Quick fix

After registering a timer callback function that calls `schedule` periodically with a 50ms frequency. The issue was resolved, and I received the results in about 1.8 microseconds.

**Comment by junyang-zh** [comment]
#990 should fix the problem
