### ISSUE TITLE
Problem encountered while refactoring API of vfs from `u8` slice to `VmReader/VmWriter`

### ISSUE THREAD

**Issue by lucassong-mh** [asterinas/asterinas#1136]
### Background 

Some file-related syscalls such as `sys_write()/sys_pread64()` requires dealing with buffers from user space.

In our current implementation in Asterinas, taking `sys_write()` as example, we do a heap allocation and a `read_bytes_from_user()` first and use this newly-allocated kernel buffer slice to do the rest work in `FileLike` and `Inode`. To avoid this unecessary copy, we can create a `VmReader` directly from current task's `VmSpace` used for subsequent processing without allocating. Through a simple test, eliminating this allocation and copy can make our cached file-io performance be on par with Linux.

To accomplish so, API in `FileLike` (and the subsequent API in `Inode`, `FileIo`, `VmIo`) looked`write(&self, buf: &[u8])` should be refactored as `write(&self, reader: &mut VmReader)`.

### Problem Statement

Things went well until I encountered:
```
error[E0308]: mismatched types
  --> /root/asterinas/kernel/aster-nix/src/syscall/write.rs:32:20
   |
32 |         file.write(&mut reader)?
   |              ----- ^^^^^^^^^^^ expected `&mut VmReader<'_>`, found `&mut VmReader<'_, UserSpace>`
   |              |
   |              arguments to this method are incorrect
   |
   = note: expected mutable reference `&mut ostd::mm::VmReader<'_, ostd::mm::KernelSpace>`
              found mutable reference `&mut ostd::mm::VmReader<'_, ostd::mm::UserSpace>`

error[E0308]: mismatched types
  --> /root/asterinas/kernel/aster-nix/src/syscall/sendfile.rs:70:48
   |
70 |             let res = in_file.read_at(*offset, &mut VmWriter::from(&mut buffer[..max_readlen]));
   |                               -------          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&mut VmWriter<'_, UserSpace>`, found `&mut VmWriter<'_>`
   |                               |
   |                               arguments to this method are incorrect
   |
   = note: expected mutable reference `&mut ostd::mm::VmWriter<'_, ostd::mm::UserSpace>`
              found mutable reference `&mut ostd::mm::VmWriter<'_, ostd::mm::KernelSpace>`
```

Different generics bring different types and slightly different behavior in `read()/write()`.
So `VmReader/VmWriter<Space = KernelSpace>` defaultly deals with buffers from kernel space rather user space, but we kindly need both abilities. For example in `trait FileLike`, we need a `read(&self, writer: &mut VmWriter<UserSpace>)` in `sys_read()` and a `read(&self, writer: &mut VmWriter<KernelSpace>)` in `sys_sendfile`, things get more often while using `trait Inode` and `trait VmIo`. To sum up, simply replacing all `u8` slice to `VmReader/VmWriter` can't satisfy our needs.

Case that `Inode::read_at()` from user space: Normal file read syscalls.
Case that `Inode::read_at()` from kernel space:
```rust
// kernel/aster-nix/src/process/program_loader/mod.rs
pub fn load_program_to_vm(
    process_vm: &ProcessVm,
    elf_file: Arc<Dentry>,
    argv: Vec<CString>,
    envp: Vec<CString>,
    fs_resolver: &FsResolver,
    recursion_limit: usize,
) -> Result<(String, ElfLoadInfo)> {
    let abs_path = elf_file.abs_path();
    let inode = elf_file.inode();
    let file_header = {
        // read the first page of file header
        let mut file_header_buffer = Box::new([0u8; PAGE_SIZE]);
        inode.read_at(0, &mut VmWriter::from(&mut *file_header_buffer))?;
        file_header_buffer
    };
    /* omitted */
}
```

Case that `VmIo::write_bytes()` from user space: Normal file write through page cache (`Vmo` inside).
Case that `VmIo::write_bytes()` from kernel space: 
```rust
// kernel/aster-nix/src/vdso.rs
impl Vdso {
    /// Construct a new Vdso, including an initialized `VdsoData` and a vmo of the VDSO.
    fn new() -> Self {
        let mut vdso_data = VdsoData::empty();
        vdso_data.init();
        /* omitted */

        // Write VDSO data to VDSO vmo.
        vdso_vmo.write_bytes(0x80, vdso_data.as_bytes()).unwrap();
        /* omitted */
    }
```

### Possible Solutions

**Extented API**
Provide double APIs such as `fn write_from_user(&self, reader: &mut VmReader<UserSpace>)` `fn write_from_kernel(&self, reader: &mut VmReader<KernelSpace>)` to serve the purpose. (Use macro to avoid repeated code as much as possible).
The drawback is the exploded trait functions not only appears in `FileLike`, but `Inode` and `VmIo`.

**Simple API with new input buffer abstraction**
Provide new input buffer abstraction such as `enum WriteBuf { FromUser(VmReader<UserSpace>), FromKernel(VmReader<KernelSpace>) }` and single API `fn write(&self, buf: &mut WriteBuf)`. At last we also need to match this enum with different behaviors.

**Encapsulate user/kernel information within `VmReader/VmWriter`**

### Linux's behavior

Not one hundred percent sure, but some code reading insights down here:

For `sys_write()/sys_preadv()` that takes pointers from user space, they all goes to `file_operations->read()/read_iter()` which treating the parametered buffers as always from user space, and calling to APIs in `include/kernel/uaccess.h` when copying to kernel buffer is needed.
As for `sys_sendfile()`, which requires copying data between two files, the workflow goes to `file_operations->ssize_t (*splice_read)(struct file *, loff_t *, struct pipe_inode_info *, size_t, unsigned int)` or the corresponding write. Note that there is a kernel pipe in the parameters for transferring kernel data, independently from the API that takes user buffer.

Learning from Linux, we can default the normal read/write API to only take buffers from user space, and think up a new API (can be a pipe) for transferring kernel data only.

---

Feel free to post your ideas of resolving this.

**Comment by cchanging** [comment]
The `VmReader`/`VmWriter` created by the file system will only be in kernel space. Maybe we can leverage this property. 

e.g. provide two kinds of API in the upper-level (like Filelike trait):
```rust
fn read_to_uer(&self, writer: &mut VmWriter<UserSpace>) -> Result<usize> {
    let read_fn = move |reader: &VmReader<KernelSpace>| {
            reader.read_fallible(writer).unwrap_or_else(|err| err.1) 
    };
    self.0.read(read_fn)
}

fn read_to_kernel(&self, writer: &mut VmWriter<KernelSpace>) -> Result<usize> {
    let read_fn = move |reader: &VmReader<KernelSpace>| {
            reader.read(writer)
    };
    self.0.read(read_fn)
}
```
and we can remain the inner API single with changes to its signature:
```rust
fn read<F>(&self, read_fn: F) -> Result<usize>
where
  F: FnMut(&VmReader<KernelSpace>) -> usize 
{
  ...
}

/// The deepest read methods
fn read<F, R>(&self, read_fn: F) -> Result<usize>
where
  F: FnMut(&VmReader<KernelSpace>) -> usize
{
    let reader = self.create_reader()?;
    let read_len = read_fn(&reader);
    ...
    Ok(read_len)
}
```

**Comment by lucassong-mh** [comment]
A newly revision in https://github.com/asterinas/asterinas/pull/1153:
```rust
/// A marker structure used for [`VmReader`] and [`VmWriter`],
/// representing their operation on the memory scope is fallible.
pub struct Fallible;
/// A marker structure used for [`VmReader`] and [`VmWriter`],
/// representing their operation on the memory scope is non-fallible.
pub struct NonFallible;

pub struct VmReader<'a, Fallibility = Fallible> {}
pub struct VmWriter<'a, Fallibility = Fallible> {}

impl<'a> VmReader<'a, Fallible> {
  pub unsafe fn from_user_space(ptr: *const u8, len: usize) -> Self {}
  
  pub fn read_fallible<F>(&mut self, writer: &mut VmWriter<'_, F>) -> core::result::Result<usize, (Error, usize)> {/* memcpy_fallible() */}
  /* read_val() */
}

impl<'a> VmReader<'a, NonFallible> {
	pub fn read(&mut self, writer: &mut VmWriter<'_, NonFallible>) -> usize {/* memcpy() */}
  
  pub fn read_fallible(&mut self, writer: &mut VmWriter<'_, Fallible>) -> core::result::Result<usize, (Error, usize)> {/* memcpy_fallible() */}
  /* read_val() and read_once() */
}

impl<'a, Fallibility> VmReader<'a, Fallibility> {
	pub unsafe fn from_kernel_space(ptr: *const u8, len: usize) -> Self {}
  /* remain(), cursor(), limit(), skip() */
}

impl<'a, Fallibility> From<&'a [u8]> for VmReader<'a, Fallibility> {
    fn from(slice: &'a [u8]) -> Self {
        unsafe { Self::from_kernel_space(slice.as_ptr(), slice.len()) }
    }
}

// Vice versa in `VmWriter`
```
