### ISSUE TITLE
Chance of subtraction overflow in clocksource

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#1160]
### Describe the bug

A job not related to the clock source implementation failed.

https://github.com/asterinas/asterinas/actions/runs/10372263948/job/28714585105

```
 [ RUN      ] ClockGettime/MonotonicVDSOClockTest.IsCorrect/CLOCK_MONOTONIC
panicked at /__w/asterinas/asterinas/kernels/comps/time/src/clocksource.rs:97:32:
attempt to subtract with overflow
```

https://github.com/asterinas/asterinas/blob/be54a39592ff60fae6e729abaa3d4a26dd7f5624/kernel/comps/time/src/clocksource.rs#L94-L102

### To Reproduce

Very rare. May not be reproducible locally.

**Comment by junyang-zh** [comment]
@boterinas triage

**Comment by tatetian** [comment]
@cchanging Could you investigate this bug? A recently merged commit also triggered this bug.

![image](https://github.com/user-attachments/assets/a43beb31-9769-40ce-b9d5-450c075a7ef2)

**Comment by junyang-zh** [comment]
https://github.com/asterinas/asterinas/actions/runs/10413814469/job/28841807785

Now in the main branch the bug is triggered.
