### ISSUE TITLE
Does RwLock need to disable preemption when acquiring a read lock?

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#1195]
### Your Question

#990 has scheduled tasks periodically, but it doesn't fix #1131 due to wrong error code when endpoints reach backlog (Ref: [af_unix.c in Linux](https://elixir.bootlin.com/linux/v6.10.4/source/net/unix/af_unix.c#L31)). After I fixed this problem and called `Thread::yield_now()` when endpoints reached backlog, the system crashed with the error message: `Switching task with preemption disabled (nesting depth: 1)`. It turns out the cause is that [the code](https://github.com/asterinas/asterinas/blob/main/kernel/aster-nix/src/net/socket/unix/stream/socket.rs#L234) calls `RwLock::read(&self)` and disabled preemption. 

So here is the question: Does RwLock need to disable preemption when acquiring a read lock? I think the user of  `RwLock::read(&self)` should recognize that multiple modules will use this method to acquire read locks, so disabling preemption doesn't seem right here. Or maybe I'm wrong because I wasn't aware of some consideration or situation the author had in designing `RwLock`.

**Comment by lrh2000** [comment]
> I think the user of RwLock::read(&self) should recognize that multiple modules will use this method to acquire read locks

What does this sentence want to mean? I don't understand this.

> so disabling preemption doesn't seem right here.

Preemption must be disabled, otherwise if the current thread holding the read lock is preempted and another thread tries to hold the write lock, it will spin until the next preemption occurs, which is wrong because it wastes a lot of CPU.

The reason the read lock needs to disable preemption is exactly the reason the write lock/spin lock needs to disable preemption. I don't think there is anything special.

**Comment by sdww0** [comment]
> > I think the user of RwLock::read(&self) should recognize that multiple modules will use this method to acquire read locks
> 
> What does this sentence want to mean? I don't understand this.
> 
> > so disabling preemption doesn't seem right here.
> 
> Preemption must be disabled, otherwise if the current thread holding the read lock is preempted and another thread tries to hold the write lock, it will spin until the next preemption occurs, which is wrong because it wastes a lot of CPU.
> 
> The reason the read lock needs to disable preemption is exactly the reason the write lock/spin lock needs to disable preemption. I don't think there is anything special.

Ok, I got it. Looks like #1196 needs to find another way to call yield_now. I will work on it.
