### ISSUE TITLE
LmBench-Pipe hang on the `main` branch

### ISSUE THREAD

**Issue by lucassong-mh** [asterinas/asterinas#1253]
### Describe the bug

On the latest main branch (commit [a72c7da](https://github.com/asterinas/asterinas/commit/a72c7dadf3b9bb680b3092af6b64084b98008cb7) by now), LmBench-Pipe test via `/benchmark/bin/lmbench/lat_pipe -P 1` or `/benchmark/bin/lmbench/bw_pipe -P 1` will hang, while enable log or maybe any other slow down moves the hang will disappear. So it's a "heisenbug" that needs to be fixed.

**Comment by StevenJiang1110** [comment]
It seems lmbench-unix-latency and lmbench-unix-connect-latency, lmbench-fifo-latency all fali due to the same reason, which can be witnessed in the benchmark CI.https://github.com/asterinas/asterinas/actions/runs/10589643579/job/29344100462

**Comment by lucassong-mh** [comment]
Fixed in https://github.com/asterinas/asterinas/pull/1257
