### ISSUE TITLE
Potential lost-wakeup in `wait.rs` during mutex unlock

### ISSUE THREAD

**Issue by tangruize** [asterinas/asterinas#1261]
### Describe the bug

In the mutex scenario, if Thread B initially holds the mutex lock and Thread A enqueues a waker in the wait queue (line 101 in `wait.rs`), followed by Thread B calling `unlock()`, the call to `wake_one()` (line 72 in `mutex.rs`) does not wake any thread because the wait queue is empty. Consequently, when Thread A holds the lock and returns (line 104 in `wait.rs`), the waker remains in the queue. If Thread C then enqueues a waker and waits (line 113), it might never be woken up because `unlock()` only wakes the first waker in the queue.

Additionally, I suspect that when a thread returns from line 104 in `wait.rs`, a waker might always be left in the queue, since the thread enqueues the waker and returns without waiting for another thread to dequeue it. Is there a mechanism to handle this that I might have missed?

https://github.com/asterinas/asterinas/blob/00d9b01d5c356fbc5f6b72b9a69a7571fdf0ab1f/ostd/src/sync/wait.rs#L99-L114
https://github.com/asterinas/asterinas/blob/00d9b01d5c356fbc5f6b72b9a69a7571fdf0ab1f/ostd/src/sync/mutex.rs#L69-L72

### To Reproduce

1. Thead B holds the mutex lock
2. Thread A attempts to acquire the lock but fails (in `wait_until()`), then enters `wait_until_or_cancelled()`.
3. Thread B releases the lock and attempts to wake a thread (but nothing happens)
4. Thread A enqueues the waker, successfully acquires the lock, and returns
5. Thread C enqueues a waker and begins waiting
6. Thread B releases the lock and wakes the first waker in the queue (Thread B itself)
7. Thread C remains unwoken

Due to the complexity of the interleaving, it's challenging to capture this scenario in a test case, so I haven't written one at this time.

### Expected behavior

No lost wakeups should occur.
(Either always `wake_all()`? or after a thread acquires the lock, there should be no leftover wakers for that thread in the wait queue.)

**Comment by jellllly420** [comment]
I don't think there is a mechanism handling this corner case in current codebase. Actually this may be the cause of some failed test like [this one](https://github.com/asterinas/asterinas/actions/runs/10595793849/job/29362332973). I once gdb'ed this hang in `test/apps/scripts/fs.sh` and found out it was caused by some sleeping tasks remaining unwoken and the kernel spinning in `init_thread`.

**Comment by tangruize** [comment]
The bug won't occur because `impl Drop for Waiter` is invoked when `wait_until_or_cancelled()` returns, setting `has_woken=true`.
