### ISSUE TITLE
How can I write a multithreading test case that truly runs in parallel?

### ISSUE THREAD

**Issue by tangruize** [asterinas/asterinas#1295]
### Your Question

Hi there!

I'm trying to write a test case for `ostd::sync::RwLock` that involves running multiple threads/tasks in true parallelism, rather than relying on manually switching thread scheduling using `yield_now()`.

### What You Have Tried

I've tried to write a `[ktest]` unit test in `rwlock.rs` using `TaskOptions::new` and also tried an integration test in test/app, which calls a syscall designed to run the test. Both approaches failed, as the threads seem to be executing in a serialized manner.

### Additional context

For example, to run one reader and one writer simultaneously.

**Comment by junyang-zh** [comment]
Currently not possible in OSTD. The `FifoScheduler` in OSTD doesn't support SMP, yet. In aster-nix `ktest` if you spawn a kernel thread and assign a CPU affinity not on this CPU the test will guaranteed to be spawned on another CPU.

**Comment by tangruize** [comment]
@junyang-zh Thank you! I will try!

**Comment by tangruize** [comment]
@junyang-zh I found that the `nproc` command prints `1`, even though I set `SMP=8` in the `make run` command. Causing my test case to panic when setting CPU affinity. How to properly increase the number of CPU cores?

**Comment by junyang-zh** [comment]
> @junyang-zh I found that the `nproc` command prints `1`, even though I set `SMP=8` in the `make run` command.

All the related system calls for SMP are not available yet. We need to implement them. Currently no one is taking this job.

**Comment by tangruize** [comment]
@junyang-zh Thank you! It's working now! I tried to run the test even when `nproc` printed `1`, but I stopped it prematurely as only the first reader was running. The issue was that setting the thread's CPU affinity to 0 ran in foreground (maybe 0 is the caller's CPU).
