### ISSUE TITLE
Why does QEMU always use 100% CPU?

### ISSUE THREAD

**Issue by tangruize** [asterinas/asterinas#1300]
### Your Question

When `make run`, QEMU always uses 100% of my CPU, quickly draining my laptop's battery. Is this expected behavior?

### What You Have Tried

- `make run`
- `make run SMP=4`
- `make run ENABLE_KVM=1`

**Comment by junyang-zh** [comment]
The idle tasks on every processors are not idle, they spin. We don't have anything like `cpu_relax()` to save power and I think it's rather not a high priority for now.

**Comment by tangruize** [comment]
I see. Thank you!
