### ISSUE TITLE
osdk: Forwarded cargo commands do not seem to work

### ISSUE THREAD

**Issue by kylerky** [asterinas/asterinas#1308]
### Describe the bug

`cargo osdk doc`, `cargo osdk clippy` and `cargo osdk check` do not work.

### To Reproduce

Simply run the commands above in the root directory, which will lead to compilation errors.

### Expected behavior

They should run without errors

### Logs

An excerpt from running `cargo osdk check`

```
error[E0463]: can't find crate for `std`
 --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/error_impls.rs:9:1
  |
9 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:290:9
    |
290 | /         compile_error!("target is not supported, for more information see: \
291 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:341:9
    |
341 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

Some errors have detailed explanations: E0433, E0463.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...

```

**Comment by junyang-zh** [comment]
The problem is, if you run `cargo osdk check` in the project workspace directory (root directory), it will apply to all the workspace members in the virtual workspace. Not all crates in the workspace are managed by the OSDK, only a part of it. The recommended usage is to use forwarded cargo commands for each crate, e.g. `cd kernel && cargo osdk check` or `cd osdk && cargo osdk doc`. You can find out about which crates are managed by OSDK in the `Makefile`. For non-OSDK managed crates, simply use `cargo check`.

**Comment by kylerky** [comment]
Thanks, those commands do work under the kernel workspace.

**Comment by tatetian** [comment]
@junyang-zh We should improve the error messages. Printing the backtrace after panicking is not quite helpful.
