### ISSUE TITLE
Stateless pollee

### ISSUE THREAD

**Issue by lrh2000** [asterinas/asterinas#1356]
### Summary

This RFC proposes to make our `Pollee` stateless.

### Context and Problem Statement

We currently maintain the I/O events in the `Pollee`. However, the `Pollee` itself does not have a lock to handle the race conditions when I/O events are modified simultaneously.
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/process/signal/poll.rs#L24-L25

Our current strategy is to hold another lock while modifying the I/O events. However, we have to take a lot of effort to manually enforce that the implementation is correct, as this is really error-prone. It also causes some nasty problems:
 - Some simple implementation strategies result in releasing the lock, regaining the lock, and re-checking the state.
 - It is also difficult to ensure that I/O events are actually updated when they should be, otherwise we may have some busy loops. 

### Proposal

This PRC proposes to remove the `events` field from the `Pollee` type. Instead, the I/O events are always computed just in time when calling the `poll` method.

### Motivation and Rationale

Here are two examples why the previous design is just annoying:

#### Pipes

When we're writing some data to a pipe writer, the "remote" reader may become available to read. To update the I/O events of the reader, we will need to hold the lock of the reader.
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/fs/utils/channel.rs#L116-L137

This is not very elegant, since all other codes except this one require only holding the writer's lock.

Meanwhile, there are two other problems:
 - As shown in the above code snippet, we want to take the writer lock _again_ in the `update_pollee` method ("again" because we already take the lock when we're writing the data). This is not very efficient.
 - It seems correct that the I/O events only need to be updated when some data is successfully written or read. However, consider the code and the following race conditions:
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/fs/utils/channel.rs#L158-L159
```
--- Task 0 --              -- Task 1 --

 [ buffer is not full ]
 [ POLLOUT = 1 ]

self.0.write() = Ok(n)

 [ buffer is full ]
 [ POLLOUT = 1 ]

 -- preempted -------->    self.0.write() = Err(EAGAIN)

                           [ buffer is full ]
                           [ POLLOUT = 1 ]

                           poll() = POLLOUT
                           self.0.write() = Err(EAGAIN)
                           poll() = POLLOUT
                           self.0.write() = Err(EAGAIN)
                           poll() = POLLOUT
                           self.0.write() = Err(EAGAIN)
                           [ Busy loop.. ]

update_pollees()  <---------- preempted --

 [ buffer is full ]
 [ POLLOUT = 0 ]
```
This race condition can be fixed by _always_ calling `update_pollee`, regardless of whether `write` fails or not. But the point is that the race conditions can _only_ be found by carefully examining the code, and it is simply better to eliminate them by the proposed `Pollee` redesign.

#### Sockets

In the current implementation, the I/O events depend on both the state of the `aster-nix` socket and `smoltcp` socket.
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/net/socket/ip/stream/mod.rs#L324-L339
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/net/socket/ip/stream/connected.rs#L125-L139

So maintaining the stateful I/O events correct is really hard. So far we use `update_io_events` to update the I/O events within a `StreamSocket` state and `init_pollee` to update the I/O events when the `StreamSocket` state changes:
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/net/socket/ip/stream/connected.rs#L120-L123

Also, since the I/O events depend on the state of both the `aster-nix` socket and the `smoltcp` socket, we need to take two locks before modifying the I/O events. To avoid deadlocks, we always take the `StreamSocket` lock first and the `SocketSet` lock second.
- This is possible if we're processing a system call from the user program. However, it's kind of awkward and not elegant to implement if we don't release the lock first.
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/net/socket/ip/stream/connected.rs#L80-L88
https://github.com/asterinas/asterinas/blob/c5009e38f12810141f1ece9d64544af59d68a3d3/kernel/src/net/socket/ip/stream/connected.rs#L125-L131
- This is not possible if we are processing a packet coming from the network. We have to hold the `SocketSet` lock first.

So in both cases we end up simply releasing the lock, getting the lock back, and checking the socket state again. This is not very flexible.

### Detailed Design

```rust
// In `FileLike`:
fn poll(&self, mask: IoEvents, poller: Option<&mut Poller>) -> IoEvents {
    // Register the poller.
    if let Some(poller) = poller {
        self.pollee.register_poller(mask, poller);
    }

    // Now the poller is registered. If any I/O events have the possibility to change, we will be
    // notified. So we don't care about race conditions between poller registration and I/O event
    // computation.

    // Compute I/O events.
    self.io_events() & mask
}
```

```rust
// In `Pollable`:
fn wait_events<F, R>(&self, mask: IoEvents, mut cond: F) -> Result<R>
where
    Self: Sized,
    F: FnMut() -> Result<R>,
{
    // Fast path:
    match cond() {
        Err(err) if err.error() == Errno::EAGAIN => (),
        result => return result,
    };

    let mut poller = Poller::new();

    loop {
	// Register the poller. We may need to expose the `register_poller`
	// method since we don't care about the I/O events returned.
        //
	// Note: This assumes that we have the new `poll` semantics as
	// described in <https://github.com/asterinas/asterinas/issues/1355>.
        let _ = self.poll(mask, Some(&mut poller));

	// Again, race conditions are fine since we've called `poll` above. In
	// other words, we'll be notified if there are new I/O events.

        match cond() {
            Err(err) if err.error() == Errno::EAGAIN => (),
            result => return result,
        };

        // We do not know the _current_ I/O events. But that is okay, because what we need is
        // to respond with _new_ I/O events.
        //
        // This will never be a busy loop, because the poller won't be woken up unless new I/O
        // events come in.
        poller.wait()?;
    }
}
```

### Alternatives Considered

I don't know of any alternatives (other than not changing anything and keeping the current implementation).

### Additional Information and Resources

The proposal conforms to the Linux implementation. For example, see [`tcp_poll`](https://elixir.bootlin.com/linux/v6.11/source/net/ipv4/tcp.c#L507).

However, we must also consider the difference between Rust and C:
 - In Linux, if we know we do not care about race conditions, we can always use `READ_ONCE` to load lock-protected states, so we can implement `poll` by computing the I/O events without actually taking a lock.
 - However, this is generally not possible in Rust, as we have to take the lock unless we are duplicating the states in some atomic variables.

### Open Questions

How will the proposed changes affect our benchmark results (mostly LMBench)?

### Future Possibilities

None.

**Comment by StevenJiang1110** [comment]
> self.io_events()

How will `self.io_events()` be calculated? Does it follow the same logic as the current `update_io_events` method?
https://github.com/asterinas/asterinas/blob/d25346342c546ee4abe4bdfc958496dfc84905c8/kernel/src/net/socket/ip/stream/connected.rs#L125-L139. 

> How will the proposed changes affect our benchmark results (mostly LMBench)?

The most significant impact is likely to be observed with selected TCP file descriptors, as this will involve selecting events from hundreds of TCP sockets. For current results, please check the section titled `[Network] The Cost of Select (TCP FDs)` at [this link](https://asterinas.github.io/benchmark/lmbench/). However, the performance decline may not pose a significant concern, as we are currently 1.66x faster than Linux. If the performance aligns more closely with Linux, it would still be acceptable.

**Comment by lrh2000** [comment]
> How will `self.io_events()` be calculated? Does it follow the same logic as the current `update_io_events` method?

Yes. The logic will be similar, of course we don't do `add_events`/`del_events`, we just return the desired I/O events.

> The most significant impact is likely to be observed with selected TCP file descriptors, as this will involve selecting events from hundreds of TCP sockets. For current results, please check the section titled `[Network] The Cost of Select (TCP FDs)` at [this link](https://asterinas.github.io/benchmark/lmbench/). However, the performance decline may not pose a significant concern, as we are currently 1.66x faster than Linux. If the performance aligns more closely with Linux, it would still be acceptable.

Thank you for the information! That's good news. I'll check the results of the TCP select benchmark before starting the implementation, as a quick check doesn't require a full refactor, just some tweaks to the `poll` implementation.

**Comment by lrh2000** [comment]
> The most significant impact is likely to be observed with selected TCP file descriptors, as this will involve selecting events from hundreds of TCP sockets. For current results, please check the section titled `[Network] The Cost of Select (TCP FDs)` at [this link](https://asterinas.github.io/benchmark/lmbench/). However, the performance decline may not pose a significant concern, as we are currently 1.66x faster than Linux. If the performance aligns more closely with Linux, it would still be acceptable.

It seems that the locking overhead is too high. In fact, if we recompute the I/O events each time `poll()` is called, the specific benchmark quickly drops to >2x slower than Linux. This also seems reasonable, since a `lock` assembly instruction typically costs tens or even hundreds of CPU cycles, which is one or more orders of magnitude slower than normal instructions.

So, our choices are:
 1. Keep the current situation. However, I believe the current situation blocks more opportunities to optimize TCP throughput for 4K messages. We currently have too many redundant locks on the normal paths, and they are hard to eliminate without this proposal.
 2. Accept the proposal. However, the `poll()`/`select()` system call performance will be significantly affected.
 3. Revise the proposal as follows: The pollee is not fully stateful, not fully stateless, but somehow in between. It _optionally_ maintains cached states.
```rust
impl Pollee {
    /// Returns the cached events at the time this method is called.
    ///
    /// This method will return `None` if the cached events are cleared by `clear_events()`.
    ///
    /// The value returned by this method may be immediately invalidated if another thread
    /// simultaneously calls `update_events()` or `clear_events()`. It's the user's responsibility
    /// to deal with this situation (e.g. by retrying or holding some locks).
    fn events(&self) -> Option<IoEvents>;

    /// Updates the cached events according to the arguments.
    ///
    /// Future calls to `events()` will return the specified events until someone calls
    /// `clear_events()` or another `update_events()`.
    ///
    /// To avoid setting the wrong events, the user usually has to hold some locks correctly.
    fn update_events(&self, events: IoEvents);

    /// Notifies observers of some events.
    ///
    /// This method calls `clear_events()` internally to clear the cached events (since they may
    /// become invalid due to the new events).
    fn notify_events(&self, events: IoEvents);

    /// Clears the cached events.
    ///
    /// Future calls to `events()` will return `None`, until someone calls `update_events()`.
    fn clear_events(&self);
}
```
So, we can:
 - Implement `poll` by:
   - If `Pollee::events()` returns a value, return it; otherwise, hold the appropriate locks, compute the events, then call `Pollee::update_events()`.
 - Implement pipes by:
   - In `write()`, trigger `notify_events(IoEvent::IN)` for the remote pollee (without holding additional locks) and trigger `clear_events()` for the local pollee (before releasing the local lock).
   - In `read()`, trigger `notify_events(IoEvent::OUT)` for the remote pollee (without holding additional locks) and trigger `clear_events()` for the local pollee (before releasing the local lock).
 - Implement TCP streams by:
   - In `send()`/`recv()`, trigger `clear_events()` for the local pollee (no re-locking required).
   - When sending a packet, trigger `notify_events(IoEvent::IN)` for the destination socket and trigger `notify_events(IoEvent::OUT)` for the source socket (no re-locking required).
