### ISSUE TITLE
PIPE implementation does not guarantee atomic writes for up to PIPE_BUF bytes

### ISSUE THREAD

**Issue by tangruize** [asterinas/asterinas#1554]
### Describe the bug

The current implementation of the PIPE in Asterinas does not ensure that writes of up to PIPE_BUF bytes are atomic. 

### To Reproduce

Apply the following patch and run `test/pipe/pipe_atomicity`

<details><summary>patch file</summary>

```diff
diff --git a/test/apps/pipe/pipe_atomicity.c b/test/apps/pipe/pipe_atomicity.c
new file mode 100644
index 00000000..1e473d78
--- /dev/null
+++ b/test/apps/pipe/pipe_atomicity.c
@@ -0,0 +1,36 @@
+// SPDX-License-Identifier: MPL-2.0
+
+#define _GNU_SOURCE
+
+#include "../network/test.h"
+#include <signal.h>
+#include <string.h>
+#include <sys/poll.h>
+#include <unistd.h>
+
+static int rfd, wfd;
+
+FN_SETUP(short_read_and_write)
+{
+       int fildes[2];
+
+       CHECK(pipe(fildes));
+       rfd = fildes[0];
+       wfd = fildes[1];
+
+}
+END_SETUP()
+
+FN_TEST(atomicity)
+{
+       char buf[511] = { 0 };
+
+       // for (int i = 0; i < 130; i++)
+       //      TEST_RES(write(wfd, buf, 511), _ret == 511);
+       for (int i = 0; i < 130; i++)
+       {
+               ssize_t res = write(wfd, buf, 511);
+               printf("i=%d, res=%ld\n", i, res);
+       }
+}
+END_TEST()
```
</details>

### Expected behavior

In the current Asterinas implementation, writing 511 bytes results in partial writes (128 bytes) after 128 iterations, while the Linux implementation blocks after 127 iterations:

![aster_vs_linux](https://github.com/user-attachments/assets/e8b9377b-fff3-4c23-bb81-8e3fa6f253e1)

### Environment

branch: [7ddfd42](https://github.com/asterinas/asterinas/tree/7ddfd42baa210656127044995d8707fde74fab4d)

**Comment by tatetian** [comment]
This one is easy to fix. Just check if the remaining space in the internal buffer of a pipe is no less than `PIPE_BUF` before actually writing the data.
