### ISSUE TITLE
Restart signal-interrupted system calls

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#1578]
### Feature Description

What happens if a POSIX signal is delivered to a thread while it is doing some blocking operation in a system call?

The expected behavior  is one of the two below:
1. Return `EINTR`, or
2. Retry the system call.

The first behavior is trivial to implement. This issue proposes to add the second one.

### Problem or Need

Allow me to quote the man page of [signal(7)](https://man7.org/linux/man-pages/man7/signal.7.html).

> If a signal handler is invoked while a system call or library function call is blocked, then either:
>
> * the call is automatically restarted after the signal handler returns; or
> * the call fails with the error EINTR.
>
> Which of these two behaviors occurs depends on the interface and whether or not the signal handler was established using the SA_RESTART flag (see [sigaction(2)](https://man7.org/linux/man-pages/man2/sigaction.2.html)).  The details vary across UNIX systems; below, the details for Linux.
>
>  If a blocked call to one of the following interfaces is interrupted by a signal handler, then the call is automatically restarted after the signal handler returns if the SA_RESTART flag was used; otherwise the call fails with the error EINTR:

System calls that will be restarted automatically if the `SA_RESTART` flag is set for the signal handlers include
* `read`, `write`, `ioctl`
* `open`
* `wait`, `waitpid`
* file locks via `fnctl`
* `futex`

In particular, we have encountered a CI failure (#1577 ) due to the wrong behavior of signal-interrupted futex system call returning `EINTR`, instead of retrying the system call automatically.

### Suggested Implementation

We need to introduce a general retry mechanism for signal-interrupted system calls. In the case of futex, Linux's futex retry logic can be found [here](https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L706).

**Comment by lrh2000** [comment]
> In particular, we have encountered a CI failure (#1577 ) due to the wrong behavior of signal-interrupted futex system call returning `EINTR`, instead of retrying the system call automatically.

Even if the `futex` system call is restarted, it will still return `EAGAIN` in the case of the failed CI in #1577. See the `futex_wait_restart` function for details.

https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L714

**Comment by lrh2000** [comment]
It is also worth noting that the restarting system call stores the [arguments in the `restart_block`](https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L707-L712), which is another motivating case for adding the thread local. Existing motivating examples include the file table (https://github.com/asterinas/asterinas/issues/1550#issue-2631657498) and lockdep (https://github.com/asterinas/asterinas/issues/1550#issuecomment-2463992806).

**Comment by tatetian** [comment]
> > In particular, we have encountered a CI failure (#1577 ) due to the wrong behavior of signal-interrupted futex system call returning `EINTR`, instead of retrying the system call automatically.
> 
> Even if the `futex` system call is restarted, it will still return `EAGAIN` in the case of the failed CI in #1577. See the `futex_wait_restart` function for details.
> 
> https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L714

In the Linux source code that you reference, the `futex_wait_restart` function calls `futex_wait` again. I can't see why this retry of `futex_wait` is doomed to return `EAGAIN`.

**Comment by lrh2000** [comment]
> In the Linux source code that you reference, the `futex_wait_restart` function calls `futex_wait` again. I can't see why this retry of `futex_wait` is doomed to return `EAGAIN`.

@tatetian  You have to follow the code as `futex_wait_restart` -> `futex_wait` -> `__futex_wait` -> `futex_wait_setup` -> [this code snippet](https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L639-L642).

So if the `uval` read from userspace is modified at the same time the signal is processed, the restarted `futex` system call will also return `EAGAIN`.

Of course, the system call test does not actually fail in Linux, because the `uval` is modified _before_ the signal is processed, so the `futex` call will simply succeed _(it will not be restarted)_.
 - Following the same principle, we should _avoid returning `EINTR`_ in this case. So whether we have the "syscall restart" mechanism or not will _not_ affect whether the CI fails (it shouldn't even be reachable if we follow the Linux implementation).

**Comment by tangruize** [comment]
I think the actual cause of the failed CI is that signals marked as `SIG_IGN` are noticed by the user program, which causes interruptions during syscalls. This behavior is inconsistent with how Linux handles ignored signals.

![TLPI_SIG_IGN](https://github.com/user-attachments/assets/82f2a221-d460-41f6-a9be-06e809c32621)

Additionally, we should also ignore `SIGCONT` if the process is not stopped and its default disposition hasn't been changed. `SIGCONT` interrupts a running process is found in https://github.com/asterinas/asterinas/issues/1542#issuecomment-2456930970 (Note: The statement about `SA_RESTART` in that comment is incorrect).

A testcase:

![testcase](https://github.com/user-attachments/assets/2ff4a3d8-305f-4b9c-beea-12b1ff4d472b)

```c
#include <stdio.h>
#include <sys/mman.h>
#include <pthread.h>
#include <linux/futex.h>      /* Definition of FUTEX_* constants */
#include <sys/syscall.h>      /* Definition of SYS_* constants */
#include <unistd.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <errno.h>
#include <string.h>
#include <sys/wait.h>

// Futex value stored at a global location
int *futex_value;

// Futex wrapper function (for Linux systems)
int futex(int *uaddr, int futex_op, int val, const struct timespec *timeout, int *uaddr2, int val3) {
    return syscall(SYS_futex, uaddr, futex_op, val, timeout, uaddr2, val3);
}

// Function for parent to wait on futex
void parent() {
    printf("Parent waiting on futex...\n");

    // Wait for futex_value to be modified (i.e., futex_value == 1)
    while (1) {
        int ret = futex(futex_value, FUTEX_WAIT, 0, NULL, NULL, 0);
        if (ret == -1) {
            // Print the error code and corresponding message if futex_wait fails
            if (errno == EINTR) {
                printf("futex_wait interrupted by signal (errno %d, %s)\n", errno, strerror(errno));
            } else {
                printf("futex_wait failed (errno %d, %s)\n", errno, strerror(errno));
                exit(1);
            }
        } else {
            printf("futex_wait successful, parent awakened!\n");
            break;
        }
    }
}

// Function for child to modify futex_value and signal the parent
void child() {
    sleep(5);

    printf("Child changing futex value...\n");

    // Change the futex value to 1
    *futex_value = 1;

    // Sleep for 5 seconds
    sleep(5);

    // Send SIGCHLD signal to parent (just for demonstration)
    printf("Child sending SIGCHLD to parent...\n");
    kill(getppid(), SIGCHLD);

    // Sleep for 5 seconds
    sleep(5);

    // Wake the parent by futex_wake
    printf("Child waking parent...\n");
    futex(futex_value, FUTEX_WAKE, 1, NULL, NULL, 0);
}

int main() {
    pid_t pid;

    // Initialize futex_value
    futex_value = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
    if (futex_value == MAP_FAILED) {
        perror("mmap failed");
        return 1;
    }
    *futex_value = 0;

    // Create the child
    pid = fork();
    if (pid == 0)
    {
        child(NULL);
    }
    else {
        parent(NULL);
    }

    return 0;
}
```

**Comment by tangruize** [comment]
The failed CI is also related to https://github.com/asterinas/asterinas/issues/1587 because it causes `futex` wake to return `1` as if it wakes up one waiting process. As a result, the assert in this line does not fail: https://github.com/google/gvisor/blob/7c2bcddc13c1729e345cfd9a75b910822e4ddcd1/test/syscalls/linux/futex.cc#L520

**Comment by tangruize** [comment]
> On the other hand, there are multiple reasons for the original CI failure. So arguing about which one is the "root" cause doesn't make much sense (and may be subjective). We'd better fix them all.

I agree that there are multiple causes of the CI failure.

**Comment by lrh2000** [comment]
> I think the CI **will** fail.

> ```c
>     // Send SIGCHLD signal to parent (just for demonstration)
>     printf("Child sending SIGCHLD to parent...\n");
>     kill(getppid(), SIGCHLD);
> 
>     // Sleep for 5 seconds
>     sleep(5);
> 
>     // Wake the parent by futex_wake
>     printf("Child waking parent...\n");
>     int res = futex(futex_value, FUTEX_WAKE, 1, NULL, NULL, 0);
>     printf("Wakeup num: %d\n", res);
> ```

This is different with the gvisor test. The gvisor test guarantees that the `SIGCHLD` will occur _after_ the `FUTEX_WAKE` call, but you send the `SIGCHLD` _before_ triggering the `FUTEX_WAKE`. I think this is just not the case with the gvisor test.

**Comment by tangruize** [comment]
> The gvisor test guarantees that the SIGCHLD will occur after the FUTEX_WAKE call, but you send the SIGCHLD before triggering the FUTEX_WAKE

Ah, that's true. I misunderstood the cleanup behavior. The CI should not fail when wakeup event and signal arrive nealy simultaneously because Linux handles it sophisticatedly (https://github.com/torvalds/linux/blob/da4373fbcf006deda90e5e6a87c499e0ff747572/kernel/futex/waitwake.c#L671-L685). But if pause_timeout returns EINTR in Asterinas, it results in different behavior comparing with Linux. Thanks for pointing it out!
