### ISSUE TITLE
`futex_wait_bitset()` should remove `futex_item` when `pause_timeout()` fails

### ISSUE THREAD

**Issue by tangruize** [asterinas/asterinas#1587]
### Describe the bug

1. When signaled or timeout, the `futex_item` is not removed from the `futex_bucket`, which can lead to lost-wakeup.
2. `waiter.pause_timeout()` returns `Ok(())` upon waking up from a signal, which can lead to incorrect handling of the wake-up event.

https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/process/posix_thread/futex.rs#L76

**Comment by lrh2000** [comment]
The [wakeup test](https://github.com/torvalds/linux/blob/2d5404caa8c7bb5c4e0435f94b28834ae5456623/kernel/futex/waitwake.c#L671-L673) must take precedence over the [pending signals test](https://github.com/torvalds/linux/blob/2d5404caa8c7bb5c4e0435f94b28834ae5456623/kernel/futex/waitwake.c#L678-L683).

This is the real cause of the failed CI due to 6421fd0b36aafb3fcd9a8f12d5bc6e89f3f86546, cc https://github.com/asterinas/asterinas/pull/1577.

I also wonder if we can remove the `pause_timeout` API and let the futex use the normal `pause_until` API, but I am not sure since I have not read the futex implementation.

> can lead to lost-wakeup.

This should only result in spurious wake?

**Comment by tangruize** [comment]
Instead of removing useless `futex_item`, we can simply skip it if `wake()` returns `false`, for such `wake_up()` call. After calling `wake_up()`, we should always check that it actually wakes one:

```diff
diff --git a/kernel/src/process/posix_thread/futex.rs b/kernel/src/process/posix_thread/futex.rs
index 316c0887..e38553b1 100644
--- a/kernel/src/process/posix_thread/futex.rs
+++ b/kernel/src/process/posix_thread/futex.rs
@@ -253,7 +253,9 @@ impl FutexBucket {
             }

             let item = item_cursor.remove().unwrap();
-            item.wake();
+            if !item.wake() {
+                continue;
+            }
             count += 1;
         }

@@ -323,8 +325,9 @@ impl FutexItem {
         (futex_item, waiter)
     }

-    pub fn wake(&self) {
-        self.waker.wake_up();
+    #[must_use]
+    pub fn wake(&self) -> bool {
+        self.waker.wake_up()
     }

     pub fn match_up(&self, another: &Self) -> bool {
```

**Comment by lrh2000** [comment]
> We do not need to change the return value as spurious wakeups are acceptable, but returning EINTR is not. This is because `FUTEX_WAIT` in Linux is automatically restarted (`SA_RESTART`, see #1578). However, we still need to handle failed cases properly.

Could you please read https://github.com/asterinas/asterinas/issues/1578#issuecomment-2466197579?

*The restarted `futex_wait` will return `EAGAIN` if we allow spurious wakeups.* This is not acceptable. *The restart mechanism is simply irrelevant to the problem and the failed CI*, as the comment above points out.

**Comment by tangruize** [comment]
> The restart mechanism is simply irrelevant to the problem and the failed CI, as the comment above points out.

@lrh2000  Thanks for pointing it out! I see it now.

The restart mechanism is irrelevant to the failed CI. The actual reason is caused by the bug described in this issue.

- The wake-up is lost due to this issue: https://github.com/google/gvisor/blob/7c2bcddc13c1729e345cfd9a75b910822e4ddcd1/test/syscalls/linux/futex.cc#L520
- During cleanup, the parent sends `SIGKILL` to the child, and then the parent self receives `SIGCHLD` (I guess). The `SIGCHLD` interrupts the `futex` wait (whose wake-up is actually lost). Because the `uval` has already changed, `futex` wait returns `-EWOULDBLOCK`.

I think we can revert "Revert 'Make pause_timeout return EINTR'" once this bug is fixed.

**Comment by lrh2000** [comment]
> the parent self receives `SIGCHLD` (I guess)

Yes. I printed the signal number when debugging the failed CI. It's `SIGCHLD`.

**Comment by tangruize** [comment]
Sorry, I might have made a mistake.

The `SIGCHLD` signal first interrupts the futex wait, and there may not have been a lost wake-up in the failed CI. The issue seems to be related to the timing of when the signal is received. It appears that the value was changed before the signal reached.

**Comment by lrh2000** [comment]
> The `SIGCHLD` signal first interrupts the futex wait, and there may not have been a lost wake-up in the failed CI. The issue seems to be related to the timing of when the signal is received. It appears that the value was changed before the signal reached.

It triggers a retry at the userspace: https://github.com/google/gvisor/blob/7c2bcddc13c1729e345cfd9a75b910822e4ddcd1/test/syscalls/linux/futex.cc#L72-L81

So, as I said, a restart mechanism won't help. The behavior will be the same as the userspace retry.

**Comment by tangruize** [comment]
> So, as I said, a restart mechanism won't help. The behavior will be the same as the userspace retry.

Yes, you are right! Let's discuss it on the original issue https://github.com/asterinas/asterinas/issues/1578#issuecomment-2470075737
