### ISSUE TITLE
Heap allocation failed due to find_free_region

### ISSUE THREAD

**Issue by Shenwenkun** [asterinas/asterinas#1589]
### Describe the bug
I am attempting to import the `torch` package into Asterias, but it dynamically links to the `libtorch` library. The `find_free_region` function searches for a free memory area; however, the direction it searches is the same as the heap's growth. As a result, the memory block it finds is located directly above the used heap memory, preventing further heap expansion.

### To Reproduce

1. Go to 'https://github.com/Shenwenkun/Trusted-AI-based-on-Rust-confidential-operating-system.git'
2. Clone the repository to your local machine
3. Execute Asterias and launch the Python interactive shell
4. enter ‘import torch’
5. See error --> 'segmentation fault'

### Expected behavior

Successfully import `torch` and can print torch.__version__

### Screenshots

![image](https://github.com/user-attachments/assets/5d630ee5-6a17-406d-9de9-3b517b5d317a)
![image](https://github.com/user-attachments/assets/b34879a1-3971-405c-846c-16c45df417b7)

### Logs
Update: The branch has been deleted but the problem still exists.

**Comment by junyang-zh** [comment]
#1557 Refactors the code and aim to remove inconsistencies introduced by the current Vma allocating algorithm. Could you please check if #1557 resolves the problem?

**Comment by junyang-zh** [comment]
You can wait for my confirmation if #1557 really resolves it. Otherwise I would fix it in #1557 by reserving a very large chunk of virtual memory space for `brk`.
