### ISSUE TITLE
[TDX] Syscall test hangs randomly

### ISSUE THREAD

**Issue by Hsy-Intel** [asterinas/asterinas#1595]
### Describe the bug

You may notice that the CI TDX syscall test often times out and fails. Checking the log, you can find that it hangs randomly during the test.

I added many print log to debug and finally find the tests mainly hang when executing some specific system calls, and roughly located the code location where they hang:

1. `sys_close`: https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/syscall/close.rs#L20

2. `sys_mmap`:
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/vm/vmar/mod.rs#L565-L571
Or:
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/vm/vmar/mod.rs#L609
Or:
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/vm/vmar/vm_mapping.rs#L781
Or:
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/vm/vmar/mod.rs#L618-L621

3. `sys_mprotect`: 
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/syscall/mprotect.rs#L45

4. `sys_munmap`:
https://github.com/asterinas/asterinas/blob/54e2ffbb71a1e4a49ce1a30e263cc8fdca6b1d7d/kernel/src/syscall/munmap.rs#L28

5. `sys_execve`:
https://github.com/asterinas/asterinas/blob/11382524d1d23cc6d41adf977a72138baa39e38d/kernel/src/syscall/execve.rs#L114-L118

6. `sys_wait4`:
https://github.com/asterinas/asterinas/blob/85d2c9634f5c4f7b3dac1f612655a5ce675a1422/kernel/src/syscall/wait4.rs#L46

7. `sys_brk`:
https://github.com/asterinas/asterinas/blob/e6c613f53841983765a7b3c56ea9958775c76199/kernel/src/syscall/brk.rs#L14

The problem does not seem to be caused by a bug in TDX itself, but may be due to some kind of data race, because when setting `LOG_LEVEL` to `info` or `debug` during testing, the hang problem almost never occurs.

**Comment by junyang-zh** [comment]
2. 3. 4. 5. may be resolved by #1557 . check again?

**Comment by Hsy-Intel** [comment]
> 2 3 4 5 may be resolved by #1557 . check again?

I tested it several times and the probability of 2 3 4 5 appearing decreased significantly, but 1 and 6 still appeared.

**Comment by Hsy-Intel** [comment]
This issue is resolved by #1637.
