### ISSUE TITLE
Allocator Hangs When Reusing Page

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#1760]
### Description

**Test Code:**

```rust
#[ktest]
fn test_raw_pages() {
    let page = Page::<FrameMeta>::from_unused(0x1000, FrameMeta::default());
    let paddr_before = page.paddr();
    drop(page);
    
    let new_page = allocator::alloc(10 * PAGE_SIZE, |_| FrameMeta::default()).unwrap();
    early_println!("new_page: {:#x}", new_page[0].paddr());
    
    let new_page = allocator::alloc(100 * PAGE_SIZE, |_| FrameMeta::default()).unwrap();
    early_println!("new_page: {:#x}", new_page[0].paddr());
    
    assert_eq!(new_page[0].paddr(), paddr_before);
}
```

**Problem Description:**

- The `Page::from_unused` method is utilized with the physical address `0x1000`.
- After using the `page`, it is dropped, which subsequently affects the allocator.
- The first allocation with `allocator::alloc(10 * PAGE_SIZE, |_| FrameMeta::default())` succeeds.
- The second allocation with `allocator::alloc(100 * PAGE_SIZE, |_| FrameMeta::default())` fails, causing the program to hang.

**Debugging Details:**

- The hang is traced to the following line in the codebase:
https://github.com/asterinas/asterinas/blob/1a5bf7b0adc203ff19d15d4be449359db5834116/ostd/src/mm/page/mod.rs#L71-L73
_Intuitively, I think this line of code should panic rather than hang._

- Additional logging at:
https://github.com/asterinas/asterinas/blob/1a5bf7b0adc203ff19d15d4be449359db5834116/ostd/src/mm/page/allocator.rs#L126-L127

<details>
<summary>Raw logs</summary>

```log
test ostd::mm::page_table::test::full_unmap_verification::test_raw_pages ...
ref_count: 0
ref_count: 1
allocating 10 pages
allocator locked
allocated page at 0x1000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x8000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x9000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x18000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x19000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x28000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x29000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x38000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x39000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x48000
ref_count: 0
ref_count: 1
pushed page
new_page: 0x1000

allocating 100 pages
allocator locked
allocated page at 0x49000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x58000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x59000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x60000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x61000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x508000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x509000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x518000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x519000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x528000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x529000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x538000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x539000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x548000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x549000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x558000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x559000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x588000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x589000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5c8000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5c9000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5d8000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5d9000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5ea000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5eb000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x768000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x769000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x778000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x779000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x8528000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x8529000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x8538000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x8539000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x7ffc8000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x7ffc9000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x560000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x561000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x562000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x563000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5ec000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5ed000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5ee000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x5ef000
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x0
ref_count: 0
ref_count: 1
pushed page
allocated page at 0x1000
ref_count: 1
```

</details>

- Observations:
  - When the program hangs, the address it attempts to allocate is `0x1000`.
  - Interestingly, using a higher address such as `0x87a8000` does not result in any issues.

**Summary:**

Using `Page::from_unused` with the physical address `0x1000` and subsequently releasing it appears to interfere with the allocator's functionality. While smaller allocations succeed, larger allocations that require the address `0x1000` cause the program to hang. However, allocating from higher memory addresses like `0x87a8000` proceeds without any problems, which never requests `0x1000`.

**Comment by junyang-zh** [comment]
Releasing a page always deallocate it in the allocator. You produced a double drop in the allocator with safe code. This is undesirable.

**Comment by junyang-zh** [comment]
I think this bug is simply fixed by making `from_unused` not public.

**Comment by grief8** [comment]
> I think this bug is simply fixed by making `from_unused` not public.

I am writing the test cases for `Page`. Does this mean all pages should be allocated from `allocator`? 

If you call `Page::<FrameMeta>::from_unused(0x1000, FrameMeta::default())` once, it would affect all subsequent tests with `allocator::alloc(100 * PAGE_SIZE, |_| FrameMeta::default()).unwrap();` where they are.

**Comment by junyang-zh** [comment]
> Does this mean all pages should be allocated from allocator?

Yes

**Comment by grief8** [comment]
> > Does this mean all pages should be allocated from allocator?
> 
> Yes

It makes sense. 
I also have another question: Why doesn’t the following code trigger a panic? Instead, it seems to hang indefinitely.
https://github.com/asterinas/asterinas/blob/1a5bf7b0adc203ff19d15d4be449359db5834116/ostd/src/mm/page/mod.rs#L71-L73

**Comment by junyang-zh** [comment]
> I also have another question: Why doesn’t the following code trigger a panic? Instead, it seems to hang indefinitely.

The third line in this block `drop(page)` clears the reference count to zero and called the frame allocator's dealloc function.

> ```rust
>     let page = Page::<FrameMeta>::from_unused(0x1000, FrameMeta::default());
>     let paddr_before = page.paddr();
>     drop(page);
> ```

So by the time the allocator calls `from_unused` it must be zero. However, the frame allocator's dealloc was called with an address that was never been allocated. So the frame allocator hangs.

**Comment by grief8** [comment]
> The third line in this block `drop(page)` clears the reference count to zero and called the frame allocator's dealloc function.
> 
> > ```rust
> >     let page = Page::<FrameMeta>::from_unused(0x1000, FrameMeta::default());
> >     let paddr_before = page.paddr();
> >     drop(page);
> > ```
> 
> So by the time the allocator calls `from_unused` it must be zero. However, the frame allocator's dealloc was called with an address that was never been allocated. So the frame allocator hangs.

I get it. Thank you for explaination!

**Comment by grief8** [comment]
> The third line in this block `drop(page)` clears the reference count to zero and called the frame allocator's dealloc function.
> 
> > ```rust
> >     let page = Page::<FrameMeta>::from_unused(0x1000, FrameMeta::default());
> >     let paddr_before = page.paddr();
> >     drop(page);
> > ```
> 
> So by the time the allocator calls `from_unused` it must be zero. However, the frame allocator's dealloc was called with an address that was never been allocated. So the frame allocator hangs.

I get it. Thank you for explanation!
