### ISSUE TITLE
How costly is disabling local IRQs

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#242]
Currently, our [spinlock](https://github.com/jinzhao-dev/jinux/blob/main/framework/jinux-frame/src/sync/spin.rs) always [disable local IRQs](https://github.com/jinzhao-dev/jinux/blob/7304e06c88c33537b6cb0e79aa77679eb179f65e/framework/jinux-frame/src/sync/spin.rs#LL83C16-L83C37). If disabling local IRQs is expensive on modern hardware, then we should make disabling local IRQs an option. One way to do this is to add an extra type parameter `P` for `SpinLock<T, P>`, where `P` is a type that abstracts that the behavior of disabling local IRQs.

**Comment by junyang-zh** [comment]
May be fixed by #1117
