### ISSUE TITLE
TLB invalidation at the right time

### ISSUE THREAD

**Issue by sdww0** [asterinas/asterinas#282]
As mentioned in 4.10.4 in Volume 3 of the Intel Manual, the processor may retain the created entries in the TLBs even after the paging structures used to create them have been modified. To ensure that linear-address translation uses the modified paging structures, Jinux should take action to invalidate any cached entries that may contain information that has since been changed.

Below are two common invalidation scenarios mentioned in the manual:

1. Software modified a paging-structure entry that maps a page, it should execute INVLPG instruction for any linear address with a page number whose translation uses that paging-structure entry.
2. Software modifies a paging-structure entry that references another paging structure. Execute INVLPG, MOV to CR3, or MOV to CR4 to modify CR4.PGE

In Jinux, the current need to invalidate the TLB consists of Map, Unmap, Protect, and a number of scenarios to change the page table mapping. We also need to consider support for the PCID in CR3.

**Comment by junyang-zh** [comment]
Tracked with #799. Closing.
