### ISSUE TITLE
Replacing the linear mapping by a alloc-on-use kernel page table

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#318]
The initial page table mapped `[0xffff8000_00000000, 0xffff8000_ffffffff]` to `[0x00000000_00000000, 0x00000000_ffffffff]`, which is 4GiB in size. The frame allocator uses addresses starting with `0xffff8*` to manage physical memory. When usable physical memory is more than 4 GiB we should add mappings for those memory in the kernel page table.

**Comment by junyang-zh** [comment]
We should implement a kernel mode page fault handler that creates new linear mappings for the kernel when there is page faults from the kernel mode.

**Comment by rviu** [comment]
Hi, I'd like to take this up. How do you go about creating the page fault handler?

**Comment by junyang-zh** [comment]
Fixed by #713.
