### ISSUE TITLE
[Preemption] A Destined Panic in `preempt()`?

### ISSUE THREAD

**Issue by fgh1999** [asterinas/asterinas#478]
# Problem?

After `disable_irq`(in line 68), a `DisabledLocalIrqGuard` is held, which contains a `DisablePreemptGuard` that has increased `PREEMPT_COUNT`.

https://github.com/jinzhao-dev/jinux/blob/0e7f279bd6b1ee4fe564c999d953a5dc1e520bf3/framework/jinux-frame/src/task/processor.rs#L66-L81

https://github.com/jinzhao-dev/jinux/blob/0e7f279bd6b1ee4fe564c999d953a5dc1e520bf3/framework/jinux-frame/src/task/processor.rs#L165-L169

The `disable_irq` is still held when entering `switch_to_task(next_task)` in line 80, and the preemptible check (in line 91) may not succeed?

https://github.com/jinzhao-dev/jinux/blob/0e7f279bd6b1ee4fe564c999d953a5dc1e520bf3/framework/jinux-frame/src/task/processor.rs#L90-L98

https://github.com/jinzhao-dev/jinux/blob/0e7f279bd6b1ee4fe564c999d953a5dc1e520bf3/framework/jinux-frame/src/task/processor.rs#L148-L150

# Solution

If the problem indeed exists, two rudimentary solutions may be:

- drop the `disable_irq` before `switch_to_task(next_task)`;
- [move the preemptible check out from `switch_to_task`](https://github.com/fgh1999/jinux/blob/cf902e58def380b993039d85016148ad8577200d/framework/jinux-frame/src/task/processor.rs#L99-L103), and add [the check](https://github.com/fgh1999/jinux/blob/cf902e58def380b993039d85016148ad8577200d/framework/jinux-frame/src/task/processor.rs#L55-L73) manually before the switch.

**Comment by fgh1999** [comment]
@skpupil It seems that it will take some more time and efforts (#563 and #564) before the fix in PR #568 is modified accordingly and scheduled to be re-reviewed.
To alleviate your suffering from the bug, you can apply the patch in #568 for local use. With `CHILD_RUN_FIRST`(deprecated in future) defaulted as `true`, the execution order of the tasks differs little from before.

**Comment by skpupil** [comment]
![image](https://github.com/asterinas/asterinas/assets/56211074/a233c233-444d-43ea-b2dd-882504ae5d6e)

This bug is easy to reproduce when I run the *sysbench* program.

@StevenJiang1110 @fgh1999
