### ISSUE TITLE
Improve the speed of stack unwinding.

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#481]
## Aspects affected

Recently the ktest framework is introduced, along with the panic uwinding capabilities of the jinux kernel itself. However, stack unwinding after panicking is noticably slow, and frequent (or abusive) use of `#[should_panic]` ktests will slow our testing process dramatically without whitelisting.

## Reason

Current implementation of exception handling languague items (specifically [_Unwind_FindEnclosingFunction](https://github.com/nbdd0121/unwinding/blob/ad1b65a9b6f5c58d45abfcac56cfd1c71c4d83ec/src/unwinder/mod.rs#L125)) would iterate over the frame discription table using [gimli::EhFrame::fde_for_address](https://docs.rs/gimli/latest/i686-unknown-linux-gnu/gimli/read/trait.UnwindSection.html#method.fde_for_address).

The frame discription table (consists of `FDE`s) have a size proportional to the code size `m`, and on every stack frame inspection all `FDE`s will be examined once, resulting in `O(nm)` time. It could be easily reduced to `O(nlogm)` using binary search.

## Possible solutions

We could do our own version of unwinding languague items or contribute to the [upstream](https://github.com/nbdd0121/unwinding) to resolve this issue.

**Comment by lrh2000** [comment]
> We could do our own version of unwinding languague items or contribute to the [upstream](https://github.com/nbdd0121/unwinding) to resolve this issue.

Perhaps we don't need this.

Assuming that we properly emit the `.eh_frame_hdr` section in our kernel binary, maybe we can enable the [`fde-gnu-eh-frame-hdr` feature](https://github.com/nbdd0121/unwinding/blob/d7cd46e009ed1dbc762dbaaf4402f57973b300bb/src/unwinder/find_fde/mod.rs#L46-L49) and I think that the `unwinding` crate will try to [do binary searching](https://github.com/nbdd0121/unwinding/blob/d7cd46e009ed1dbc762dbaaf4402f57973b300bb/src/unwinder/find_fde/gnu_eh_frame_hdr.rs#L41-L52) automatically.
