### ISSUE TITLE
Support for in-kernel sleep

### ISSUE THREAD

**Issue by chenIshi** [asterinas/asterinas#625]
Currently sleep function we provide seems to be the only `pauser.pause_until_or_timeout()` for the POSIX threads from users, as in the `clock_nanosleep` syscall. However, some functionalities within kernel also need sleep like
https://github.com/asterinas/asterinas/blob/bd6f65667df494f6fb88fc60eb4ed18a106bed71/services/libs/aster-std/src/net/iface/util.rs#L49-L76
Without the support for kernel-level sleep, the polling would consume all the CPU cycles just to busy polling, while there is already hint for how long it should wait.

**Comment by tatetian** [comment]
In-kernel sleep is supported. A kernel thread can sleep using the `WaitQueue` API provided by the Framework. `Pauser` is in fact based on `WaitQueue`.

In theory, the specific code snippet you show can and should be refactored using `WaitQueue` to avoid busy looping. But it is written that way. Why? My guess is that at the time when this busy loop is written, the timer API of the Framework is not ready.

```rust
// FIXME: use timer or wait_timeout when timer is enable. 
```

@StevenJiang1110 is the original author so his answer is the most wanted.

**Comment by StevenJiang1110** [comment]
Yes, the origin code is added when `WaitQueue` cannot accept a `timeout` parameter.  Since timeout is supported now, we can avoid using busy loop here. #630 provides a fix for this problem.
