### ISSUE TITLE
[BUG] `cargo doc` reports error and fails

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#657]
# Problem
`cargo doc` is used in `make docs` to generate API documentations. However, the command will fail currently. The problem seems to exist for a long time.

Before introducing OSDK, the `inventory` crate will report error. Since this crate is forked under Asterinas, we shoube be able to fix the error. 

![iwEcAqNwbmcDAQTRCfIF0QJ2BrCwmeF5_LlFWwXOjUHN7ecAB9MAAAAAuoBoxQgACaJpbQoAC9IABSn4 png_720x720q90](https://github.com/asterinas/asterinas/assets/27764680/f2ccc7b8-a924-402b-b67b-76c3b5a5496f)

After indroducing OSDK, new problem occurs. The `linux-bzimage-setup` panics when running `cargo doc`. 

<img width="1458" alt="截屏2024-02-29 15 30 54" src="https://github.com/asterinas/asterinas/assets/27764680/97c6f89c-419d-46d6-9045-ea515fe80b3c">

If running `cargo doc --target x86_64-unknown-none` to avoid panic in `linux-bzimage-setup` , more error occurs.

# Possible solution

1. Fix the error in `inventory`
2. Make `linux-bzimage-setup` can also build under other target, like `x86_64-unknown-linux-gnu`, but should we allow this behavior?

**Comment by junyang-zh** [comment]
This will work.

```bash
cargo doc --target x86_64-unknown-none -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem
```
