### ISSUE TITLE
[BUG] API fopen doesn't work

### ISSUE THREAD

**Issue by skpupil** [asterinas/asterinas#664]
I wrote a simple program using the fopen api that worked fine on linux, but reported an error on asterinas

**Comment by skpupil** [comment]
```
#include <stdio.h>

int main() {
    // 文件名
    const char *filename = "test.txt";

    // 尝试打开文件
    FILE *file = fopen(filename, "r");

    // 检查文件是否成功打开
    if (file == NULL) {
        perror("Error opening file");
        return 1; // 返回非零表示发生错误
    }

    // 读取并打印文件内容
    char buffer[256];
    while (fgets(buffer, sizeof(buffer), file) != NULL) {
        printf("%s", buffer);
    }

    // 关闭文件
    fclose(file);

    return 0; // 返回零表示成功
}
```

**Comment by skpupil** [comment]
![image](https://github.com/asterinas/asterinas/assets/56211074/59721a21-bc98-422f-8a21-20d58edc7093)

**Comment by StevenJiang1110** [comment]
@skpupil, could you please try the patch in #623?

**Comment by skpupil** [comment]
> @skpupil, could you please try the patch in #623?
d
It work!!! 
By the way, maybe this patch should be rebased on the latest directory structure.

**Comment by StevenJiang1110** [comment]
> By the way, maybe this patch should be rebased on the latest directory structure.

@skpupil, thanks for verifying the patch. The patch is rebased now.
