### ISSUE TITLE
Feature Request: Implement Mount System Call Wrapper

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#737]
# Rationale
I have noticed that the current implementation lacks a system call wrapper for `mount` although we are able to mount filesystems like `ext2`. Given the significance of the mount operation in Unix-like operating systems, I believe it would be beneficial to the project to have this functionality.

I would like to propose the addition of a `mount` system call wrapper, and I'm willing to work on its implementation. 

# Proposal
Following the `mount` in Linux, we have the following abstraction in Asterinas: 
```
/// Mounts a filesystem to the specified directory.
///
/// This function wraps the `mount` system call, allowing you to attach a filesystem to
/// the file hierarchy at a specified mount point.
///
/// # Arguments
/// * `dev_name` - Path to the device or filesystem source. For non-device mounts
///                (like bind mounts), this should point to the directory to be
///                mounted.
/// * `dir_name` - Path to the directory where the filesystem will be mounted.
/// * `fs_type`  - Type of the filesystem to mount (e.g., "ext4", "tmpfs").
/// * `flags`    - Mount flags specifying mount options. These are bitwise-ORed 
///                together from `MountFlags`.
/// * `data`     - Filesystem-specific data that is passed to the kernel. The format
///                and meaning varies depending on the filesystem.
///
/// # Returns
/// A `Result` containing a `SyscallReturn` that indicates the status of the operation.
/// On success, the `SyscallReturn` typically contains integer value `0`. On error,
/// a variant containing the appropriate error code is returned.
///
/// # Example
/// ```
/// use your_crate::MountFlags;
///
/// let result = sys_mount("/dev/sda1", "/mnt", "ext2", MountFlags::MS_RDONLY, None);
/// match result {
///     Ok(_) => println!("Mount successful!"),
///     Err(err) => eprintln!("Mount failed: {:?}", err),
/// }
/// ```
///
/// # Safety
/// This function is inherently unsafe as it performs a syscall that requires
/// administrative privileges. Also, passing incorrect or malicious parameters
/// could lead to instability or security vulnerabilities.
///
/// # Errors
/// This function will return an error if the mount operation fails for reasons
/// such as invalid parameters, insufficient permissions, or unavailable device.
/// The specific error codes are defined by the underlying 
///
/// # Implementation Notes
/// Depending on the mount flags, this function sets up `mnt_flags` and `sb_flags`
/// for further mount configuration. The main handler functions invoked by this
/// multiplexer include:
/// - `do_reconfigure_mnt` to modify mount options.
/// - `do_loopback` to perform loopback mounts.
/// - `do_change_type` to change filesystem types.
/// - `do_move_mount` to move an already mounted filesystem.
/// - `do_new_mount` to mount a new filesystem. This is the primary focus of the
///   explanation for this function.
///operating system.
pub fn sys_mount(
    dev_name: &str,
    dir_name: &str,
    fs_type: &str,
    flags: MountFlags,
    data: Option<&str>,
) -> Result<SyscallReturn> {
    // ...
}
```

---

Before proceeding, I wanted to discuss the following:

1. Is there any existing work or planned work for this feature?
2. Are there specific guidelines or design patterns the project prefers for system call wrappers?

**Comment by tatetian** [comment]
Thanks for the proposal. You are welcome to adding the mount system call.

Here are my initial feedbacks.

> /// This function wraps the `mount` system call, allowing you to attach a filesystem to
> /// the file hierarchy at a specified mount point.

Calling a wrapper is inappropriate. It does not wrap the system call; it implements the system call.

> /// # Safety

As a convention, a `Safety` section is added to describe the preconditions of an `unsafe` function. But this function is not unsafe. So this section should be removed.

> /// # Implementation Notes

Please do not include "Implementation Notes" section in Rust docs, which are supposed to describe the behaviors and contract of an API, not elaborate on its implementation.

If this issue is positioned as a design doc, then it should describe how `do_reconfigure_mnt`, `do_loopback`, etc., are implemented in a high level. Giving only the names of a bunch of internal functions is not helpful to anyone.

> pub fn sys_mount(
    dev_name: &str,
    dir_name: &str,
    fs_type: &str,
    flags: MountFlags,
    data: Option<&str>,
) -> Result<SyscallReturn> 

The `data` argument can be an arbitrary sequence of bytes, which cannot be represented by `&str`.

**Comment by grief8** [comment]
> Calling a wrapper is inappropriate. It does not wrap the system call; it implements the system call.
> 
> >

Thank you for your reply!

I will wrap the syscall by `syscall_handler!(5, sys_mount, args)` like other syscalls, and modify the comments with the later pull request.

**Comment by StanPlatinum** [comment]
You can check on #855  about this issue. And any input will be appreciated!
