### ISSUE TITLE
Acquire `Mutex` in vmo after a spin-rwlock in RamFS

### ISSUE THREAD

**Issue by fgh1999** [asterinas/asterinas#746]
A rwlock, `self_inode`, is acquired at line 479.

https://github.com/asterinas/asterinas/blob/a60a8ad3e1218df9516999dbbdfb01223eea2be2/kernel/aster-nix/src/fs/ramfs/fs.rs#L474-L496

However, `Vmo_::resize()` in `Vmo::resize()` (line 487⬆️) acquires a `Mutex` lock (line 486⬇️). The vmo `Pages` are guarded internally by `Mutex`, maybe they should not be used after a spin(rw)locked resource.

https://github.com/asterinas/asterinas/blob/a60a8ad3e1218df9516999dbbdfb01223eea2be2/kernel/aster-nix/src/vm/vmo/mod.rs#L478-L496

Currently, I didn't observe any context switch that is triggerred by the mutex lock(`pages.lock()`), which means the `schedule()` in `wait()` is not called. Well, the usage above seems not right, hope I don't get it wrong this time(
Actually for this problem, I am not sure whether it is related to fs or vm...

**Comment by liqinggd** [comment]
In `VMO`, `Mutex` is used because there may be I/O during page commit; hence, a `Mutex` is required. However, in the context of `RamFS`, there is no I/O during Page commit since it is a memory-based file system.

**Comment by tatetian** [comment]
> In `VMO`, `Mutex` is used because there may be I/O during page commit/decommit; hence, a `Mutex` is required. However, in the context of `RamFS`, there is no I/O during Page commit/decommit since it is a memory-based file system.

Mutex/RwMutex must NOT be used after acquiring SpinLock/RwLock regardless of whether you are doing I/O or not. The point is not about doing I/O, but sleeping. Acquiring Mutex/RwMutex may cause the thread to sleep. This may cause deadlock for the same reason as doing I/O.

**Comment by liqinggd** [comment]
> > In `VMO`, `Mutex` is used because there may be I/O during page commit/decommit; hence, a `Mutex` is required. However, in the context of `RamFS`, there is no I/O during Page commit/decommit since it is a memory-based file system.
> 
> Mutex/RwMutex must NOT be used after acquiring SpinLock/RwLock regardless of whether you are doing I/O or not. The point is not about doing I/O, but sleeping. Acquiring Mutex/RwMutex may cause the thread to sleep. This may cause deadlock for the same reason as doing I/O.

OK, then acquire Mutex in vmo after a spin-rwlock is not correct, I will fix the lock type.
