### ISSUE TITLE
Deliver POSIX signals for busy-loop user code

### ISSUE THREAD

**Issue by tatetian** [asterinas/asterinas#774]
## Problem

Currently, the POSIX signals are handled in the main loop of user tasks, after `UserMode::execute` returns.

```rust
pub fn create_new_user_task(user_space: Arc<UserSpace>, thread_ref: Weak<Thread>) -> Arc<Task> {
    fn user_task_entry() {
        loop {
            let user_event = user_mode.execute();
            
            let context = user_mode.context_mut();
            handle_user_event(user_event, context);
            
            let current_thread = current_thread!();
            if current_thread.status().lock().is_exited() {
                break;
            }
            // POSIX signals are handled here!
            handle_pending_signal(context).unwrap();
            
            // ...
        }
    }
    
    TaskOptions::new(user_task_entry)
        .data(thread_ref)
        .user_space(Some(user_space))
        .build()
        .expect("spawn task failed")
}
```

This means that if `UserMode::execute` does not returns, then the kernel has no chance to handle signals. Consider the following simple user program in C.

```rust
int main() {
    // When the one second elapses, a SIGALRM will be triggered.
    // The default behavior of a process when receiving SIGALRM
    // is to terminate the process.
    alarm(1);
    // But currently, the busy loop will prevent the program
    // from being terminated!
    while (1) { }
    return 0;
}
```

Of course. The `SIGALRM` shall never be delivered to the process by Asterinas as the kernel can only handles POSIX signals when the user code requests system calls.

## Analysis

To figure out a solution, let's dig into the `UserMode::execute` function, which calls `UserContext::execute` to do the real job.

```rust
fn execute(&mut self) -> crate::user::UserEvent {
    // ...
    
    loop {
        self.user_context.run();
        match CpuException::to_cpu_exception(self.user_context.trap_num as u16) {
            Some(exception) => {
                if exception.typ == CpuExceptionType::FaultOrTrap
                    || exception.typ == CpuExceptionType::Fault
                    || exception.typ == CpuExceptionType::Trap
                {
                    break;
                }
            }
            None => {
                if self.user_context.trap_num as u16 == SYSCALL_TRAPNUM {
                    break;
                }
            }
        };
        call_irq_callback_functions(&self.as_trap_frame());
    }

    if self.user_context.trap_num as u16 != SYSCALL_TRAPNUM {
        // ...
        
        UserEvent::Exception
    } else {
        UserEvent::Syscall
    }
}
```

If the periodic timer interrupt is triggered while the CPU is running in the user mode, then `self.user_context.run()` returns and the interrupt is handled by the `call_irq_callback_functions` function.

So the control of the CPU does return to the kernel at regular intervals. However, a significant issue arises with the `UserContext::execute` method from the Asterinas Framework—it lacks awareness and handling of POSIX signals, and appropriately so.

### Major changes to `aster-frame`

So this issue proposes to extend the API of the `UserMode::execute` method as well as that of `UserContext::execute` so that the two methods would return the control of the CPU to its caller (e.g., the `aster-nix` crate) if there are pending events (e.g., POSIX signals).

The new interface is as shown below.

```rust
impl<'a> UserMode<'a> {
    /// Starts executing in the user mode. Make sure current task is the task in `UserMode`.
    ///
    /// The method returns for one of three possible reasons indicated by `ReturnReason`.
    /// 1. A system call is issued by the user space;
    /// 2. A CPU exception is triggered by the user space;
    /// 3. A kernel event is pending, as indicated by the given closure.
    ///
    /// After handling whatever user or kernel events that 
    /// cause the method to return
    /// and updating the user-mode CPU context,
    /// this method can be invoked again to go back to the user space.
    fn execute<F>(&mut self, mut has_kernel_event: F) -> ReturnReason 
    where
        F: FnMut() -> bool,
    {
        // ...
    }
}
```

The new `ReturnReason` replaces the old `UserEvent`.

```rust
/// A reason as to why the control of the CPU is returned from
/// the user space to the kernel.
#[derive(PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum ReturnReason {
    /// A system call is issued by the user space.
    UserSyscall,
    /// A CPU exception is triggered by the user space.
    UserException,
    /// A kernel event is pending 
    KernelEvent,
}
```

### Major changes to `aster-nix`

The main loop of a user task is modifed to utilize the extended interface of `UserMode::execute`.

```rust
fn execute(&mut self) -> crate::user::UserEvent {
    // ...

    fn user_task_entry() {
        let has_kernel_events_fn = {
            let current = current!();
            let current_thread = current_thread!();
            || {
                current.has_pending_signals()
            }
        };
        
        loop {
            let return_reason = user_mode.execute(has_kernel_events_fn);
            let context = user_mode.context_mut();
            match user_event {
                ReturnReason::UserSyscall => handle_syscall(context),
                ReturnReason::UserException => handle_exception(context),
                _ =>,
            }

            let current_thread = current_thread!();
            if current_thread.status().lock().is_exited() {
                break;
            }
            handle_pending_signal(context).unwrap();
            // ...
        }
    }

    // ...
}
```

**Comment by jellllly420** [comment]
I made some modification in #782 to enable timely delivery of POSIX signals based on the solution you proposed. But as to this specific MRE that you mentioned,
```c
int main() {
    // When the one second elapses, a SIGALRM will be triggered.
    // The default behavior of a process when receiving SIGALRM
    // is to terminate the process.
    alarm(1);
    // But currently, the busy loop will prevent the program
    // from being terminated!
    while (1) { }
    return 0;
}
```
I'm afraid that's not enough. 

Under current implementation of alarm syscall, the actual callback, in which we enqueue the `SIGALRM` to corresponding `posix_thread`'s `sig_queues`, is submitted to the global workqueue once the timer expires. However, our scheduler doesn't support preemption, therefore the submitted workitem will never be executed.

**Comment by StevenJiang1110** [comment]
> Under current implementation of alarm syscall, the actual callback, in which we enqueue the SIGALRM to corresponding posix_thread's sig_queues, is submitted to the global workqueue once the timer expires. However, our scheduler doesn't support preemption, therefore the submitted workitem will never be executed.

@jellllly420, there's a preemption point in the main loop of `user_task_entry`, after handling pending signal. So the workqueue thread should be scheduled to run after some signal is submitted the the work queue?

**Comment by jellllly420** [comment]
> > Under current implementation of alarm syscall, the actual callback, in which we enqueue the SIGALRM to corresponding posix_thread's sig_queues, is submitted to the global workqueue once the timer expires. However, our scheduler doesn't support preemption, therefore the submitted workitem will never be executed.
> 
> @jellllly420, there's a preemption point in the main loop of `user_task_entry`, after handling pending signal. So the workqueue thread should be scheduled to run after some signal is submitted the the work queue?

Will the `Usermode::execute` in `user_task_entry` ever return once we enter the `while(1)` busy-looping?

**Comment by StevenJiang1110** [comment]
> Will the Usermode::execute in user_task_entry ever return once we enter the while(1) busy-looping?

Currently, it won't. Maybe the `has_kernel_events_fn` should also check whether there are any pending workitems, and if any, it should also return to aster-nix.

**Comment by tatetian** [comment]
Preemptive scheduling, as opposite to cooperative scheduling, is by definition transparent to the tasks that are subject to scheduling. In other words, Asterinas Framework must enforce preemption, without cooperation from the users of Asterinas Framework.

But in our current implementation, the `preempt` method from `aster-frame` is explicitly called by its user.

```rust
pub fn create_new_user_task(user_space: Arc<UserSpace>, thread_ref: Weak<Thread>) -> Arc<Task> {
    fn user_task_entry() {
        loop {
            let user_event = user_mode.execute();
            let context = user_mode.context_mut();
            handle_user_event(user_event, context);

            // ...

            // a preemption point after handling user event.
            preempt();
        }
        // ...
    }
    // ...
}
```

I think the `aster_frame::task::preempt` function should be made private and called internally in `UserMode::execute`.

**Comment by jellllly420** [comment]
Thanks for your advice.

I have some question about how the `WorkQueue` mechanism works after we submit some `WorkItem`s. If I understood  correctly, the `Monitor` of `WorkerPool` should be scheduled to run first and the `Monitor` will `wake_worker` or `add_worker`, then we should wait for the running worker to be scheduled and the `Worker` will pick a  `WorkItem` to run if there is any. If that was the case, how can a `Monitor` of `normal` priority preempt a running thread in current `PriorityScheduler`?

**Comment by jellllly420** [comment]
Update:

When I replaced `preempt` with `schedule`, the `Monitor` can be scheduled to run. However, `Workers` waken by `Monitor` still cannot be scheduled even though they are supposed to be of real-time priority. It's caused by #790.

After fixing that issue, the `SIGALRM` signal can finally be correctly enqueued. I expected that the `while(1)` thread would be rescheduled to run and the signal would be handled in next timer interrupt. The `while(1)` did get on the cpu. However, this time the `UserContext::run` never returned. I'm not that familiar with this part and need to dig in more to find out what happened.

**Comment by tatetian** [comment]
> When I replaced `preempt` with `schedule`, the `Monitor` can be scheduled to run. However, `Workers` waken by `Monitor` still cannot be scheduled even though they are supposed to be of real-time priority. It's caused by #790.

Good point 👍
