### ISSUE TITLE
something wrong with make run command

### ISSUE THREAD

**Issue by dahefanteng** [asterinas/asterinas#813]
i run the docker and run "make build" successful in the docker, but when i run  "make run" command, it output the error below:
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
WARNING: no console will be available to OS
error: no suitable video mode found.
[kernel] finish init aster_frame
Loopback ipaddr: 127.0.0.1
DHCP update IP address: Address([10, 0, 2, 15])
Default router address: Address([10, 0, 2, 2])
[kernel] unpacking the initramfs.cpio.gz to rootfs ...
[kernel] rootfs is ready
[ERROR]: Uncaught panic!
panicked at /root/asterinas/kernel/aster-nix/src/vdso.rs:184:63:
called `Result::unwrap()` on an `Err` value: Error { errno: ENOENT, msg: None }

and indeed i can not find the vdso.so in anywhere,so should i do some extra actions to make it work?

**Comment by StevenJiang1110** [comment]
Do you use the latest main branch?

The problem may happen if you fail to download vdso.

Maybe you can try `make clean` and `make run` again.  After `make clean`, `make run` will try downloading vdso again.
