### ISSUE TITLE
[Performance] The slowness of `trapframe` leads to a slowdown in handling syscalls.

### ISSUE THREAD

**Issue by liqinggd** [asterinas/asterinas#842]
We validated the overhead associated with system calls themselves through benchmarking `getpid`. After our recent performance optimizations, the latest performance data for `getpid` is as follows:
![image](https://github.com/asterinas/asterinas/assets/49150782/dbe3e385-d35d-4bd7-9626-8eb707ad2d61)

As can be seen, the primary performance bottleneck lies in the `trapframe` part. `trapframe` is a third-party crate implemented in Rust, whose primary use is to handle the trap frame across kernel and user space. We need to compare it with the relevant Linux implementation and try to identify points for performance optimization, in order to further elevate our performance.

The code of `trapframe` is https://github.com/asterinas/trapframe-rs

**Comment by cqs21** [comment]
With this fix: https://github.com/cqs21/trapframe-rs/commit/b1fd1f69f7ec5e6553652f6a97de4209f1f41955, the overhead of `getpid` could reduce to ~570 cycles.
![getpid-with-fix](https://github.com/asterinas/asterinas/assets/88015902/237e4649-8430-4aa7-9492-11c9c5a60016)
