### ISSUE TITLE
CI occationally fails when running regression test

### ISSUE THREAD

**Issue by StevenJiang1110** [asterinas/asterinas#856]
The log can be viewed at https://github.com/asterinas/asterinas/actions/runs/9121975779/job/25082012079. 

The bug seems to be caused by the system failing to boot and hanging up before running the test. However, I am unable to reproduce the bug locally. Therefore, I have opened this issue to document it. 

The occurrence of this bug is not intentional. However, I have also observed it several times in #615, for example: 

https://github.com/asterinas/asterinas/actions/runs/9111370548 

However, as #615 is not related to regression testing, I am unsure why this issue is occurring.

<img width="1089" alt="截屏2024-05-17 12 03 48" src="https://github.com/asterinas/asterinas/assets/27764680/7ed6cd5b-29a1-46d2-8a6e-9ce1f3ab0ee6">

**Comment by grief8** [comment]
#784 and #841 also fail to pass this integration test.

**Comment by grief8** [comment]
I find that adding `make clean` before `make run AUTO_TEST=regression ENABLE_KVM=0 BOOT_PROTOCOL=multiboot2 RELEASE=1` in CI can solve this problem. Maybe this error comes from intermediate of previous compiling processes.

**Comment by StevenJiang1110** [comment]
Done
