### ISSUE TITLE
iperf3 get heap allocation error because of big backlog 

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#866]
When I run `iperf3 -s -B 10.0.2.15 -p 6777 -1 1>/dev/null &`, I get the following error: 
```log
[ERROR]: Uncaught panic!
panicked at /root/asterinas/framework/aster-frame/src/vm/heap_allocator.rs:26:5:
Heap allocation error, layout = Layout { size: 65536, align: 1 (1 << 0) }
```

This error comes from the `ListenStream` of the current socket implementation. It may use an excessively large `backlog`, consume all heap memory, and cause the system to crash. This problem is also proposed by #456 .

I think setting `backlog` to a small number and increasing it on demand may be more reasonable.

**Comment by lrh2000** [comment]
@grief8 Could you please explain why you closed this issue?

I don't think the problem has been fixed. So, could you please reopen it?

**Comment by grief8** [comment]
> @grief8 Could you please explain why you closed this issue?
> 
> I don't think the problem has been fixed. So, could you please reopen it?

Of course.
