### ISSUE TITLE
[RFC] Add Auto-labeling Bot for Issue/Pull Request Management

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#886]
## Summary

This RFC (Request for Comments) proposes the integration of an auto-label bot into our GitHub repository workflow. The bot will automatically add labels to issues and pull requests based on specific keywords mentioned in comments. The goal is to streamline the triage process and make managing issues and PRs more efficient.

## Motivation

As our project grows, the volume of issues and pull requests can become overwhelming for maintainers to manage manually. Implementing an auto-label bot would help with:
- Reducing the manual effort required to label issues and PRs.
- Speeding up the triage process by automatically categorizing issues based on community and maintainer comments.
- Improving issue discoverability and organization, making it easier for contributors to find relevant issues and PRs to work on.

## Detailed Design

The auto-label bot will be triggered whenever a new comment is added to an issue or pull request. Upon activation, the bot will search the comment for predefined keywords linked to specific labels. If a match is found, the bot will automatically add the corresponding label to the issue or PR.

For example:
- Comment containing the keyword "bug" will trigger the addition of the "bug" label.
- Comment containing the keyword "enhancement" will trigger the addition of the "enhancement" label.

The bot shall support an extensible configuration allowing maintainers to define their own keyword-label pairs.

**Implementation Steps:**
1. Define a YAML file within the `.github/workflows/` directory to specify the bot's trigger conditions and corresponding actions.
2. Create a list of keyword-label pairs for the bot to monitor.
3. Set up the bot using GitHub Actions with a script or using a third-party bot service like Probot to listen to comments and manage labels.
4. Test the bot on a set of issues and PRs to ensure it functions as expected.
5. Document the bot's functionality and usage guidelines to assist maintainers and contributors.

## Rationale and Alternatives

Automating the labeling process helps maintainers focus more on reviewing code and addressing substantive issues rather than on administrative tasks. While this could be done manually by maintainers, automation reduces errors and delays.

An alternative approach is to rely on existing community solutions like Probot. However, creating a custom bot using GitHub Actions provides flexibility and integration directly within our repository without external dependencies. 

## Prior Art

Similar bots have been used in various open source projects to great effect, helping maintainers keep their repositories well-organized and contributors informed about potential areas of contribution, e.g., LLVM.

## Unresolved Questions

- What is the exact set of keywords and their corresponding labels that we want to use? For example, LLVM defines the keywords according to the directories. We can have `aster-frame`, `ktest`, `osdk`, etc.
- ~~How will we handle edge cases where multiple or conflicting labels might be required? I cannot figure out an example now.~~

## Future Possibilities

Once the auto-label bot is successfully implemented, we may consider expanding its capabilities to include automatic assignment of reviewers or auto-closing stale issues based on specific conditions.

---

Welcome all feedback, suggestions, and contributions from the community to finalize the design and implementation of the auto-label bot.

**Comment by junyang-zh** [comment]
Shall we just opt the [Rust's label format](https://forge.rust-lang.org/release/issue-triaging.html#labels), like:
 - `S-need-review`;
 - `bug`/`feat`/`perf`;
 - `A-mm`/`A-net`/`A-fs`;
 - `T-x86`/`T-tdx`/`T-riscv`.

**Comment by grief8** [comment]
> Shall we just opt the [Rust's label format](https://forge.rust-lang.org/release/issue-triaging.html#labels), like:
> 
> * `S-need-review`;
> * `bug`/`feat`/`perf`;
> * `A-mm`/`A-net`/`A-fs`;
> * `T-x86`/`T-tdx`/`T-riscv`.

Good idea! I think we can also add `fix` and `help`.

**Comment by StevenJiang1110** [comment]
Another place that enables auto-labeling is use the Github issue template. 

The Rust community provides several [issue templates](https://github.com/rust-lang/rust/tree/master/.github/ISSUE_TEMPLATE), and if the user uses a template, a default label will be added. 

For example, the [bug-report](https://github.com/rust-lang/rust/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1) template will add the `C-bug` label by default.
