### ISSUE TITLE
[RFC] Overview of new labels and issue templates

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#911]
Thanks for your comments about the Asterinas labels management @tatetian @lrh2000 @junyang-zh @StevenJiang1110. And this issue gives a detailed elaboration about labels in #886.

---

## Label Classification
1. Issue labels: 
- `C-bug`: report bugs or unusual behavior in the project
- `C-feature-request`: Suggest new features or improvements
- `C-enhancement`: optimization and improvement suggestions
- `C-documentation`: documentation related issues or improvements
- `C-question`: Ask questions related to the project
- `C-tracking-issue:` track the progress of a specific task or feature
- `C-duplicate`: duplicate issue
- `C-good-first-issue`:  first issue suitable for novices to participate in
- `C-need-triage`: issues cannot be recognized.

2. Priority labels: 
- `P0 --> P4` : From highest priority to lowest priority

3. Status labels: 
- `S-confirmed`: Confirmed issue or accepted feature request
- `S-invalid`: invalid question
- `S-wontfix`: Problems that will not be fixed
- `S-stale`: Questions that no one has followed up on for a long time

4. PR  labels:
- `O-dependency`: PR related to dependency library update
- `O-bugfix`: PR to fix the bug
- `O-feature`: PR to implement new features
- `O-refactor`: PR related to code refactoring
- `O-test`: PR to add or improve tests

### Auto-labeling

The workflow will identify the issues and PRs and tag them with the labels below automatically.
- Labels associated with issue template: `C-bug, C-feature-request, C-enhancement, C-documentation, C-question, C-tracking-issue`
- Labels associated with PR title: `O-bugfix, O-dependency, O-feature, O-refactor, O-test`

### Bot-labeling

Committers can also add these labels by @labeller-bot.
- Issue: `C-duplicate` 
- State: `S-stale`
- Others: `C-need-triage`

### Maintainer-labeling

Only Maintainers can add the following labels
- Priority: `P0, P1, P2, P3, P4`
- State: `S-confirmed, S-invalid, S-wontfix, C-good-first-issue`

### Bug
```md
---
name: Bug Report
about: Create a bug report to help us improve our operating system.
title: '[BUG] Brief description of the problem'
labels: 'C-bug'
assignees: ''

---

<!-- Thank you for taking the time to report a bug. Your input is valuable to us.
Please replace all the <angle brackets> below with your own information. -->

### Describe the bug

<!-- A clear and concise description of what the bug is. -->

### To Reproduce

<!-- Steps to reproduce the behavior. Example:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error -->

### Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

### Log

<!-- If applicable, add logs or screenshots to help explain your problem. -->

### Environment

<!-- Please fill out this information as completely as possible:
- Hardware platform (e.g., Intel(R) Xeon(R) Gold 6342 CPU):
-->

### Additional context

<!-- Add any other context about the problem here. For example, did the issue start occurring recently or has it always been there? -->

### Backtrace

<!-- If applicable, add log snippets or files to help explain and debug the problem. Please use code blocks (```) to format logs. -->

<!-- Once again, thank you for helping us improve our project! -->

```

### Feature Request
```md
---
name: Feature Request
about: Propose a new feature to add to this operating system
title: '[FEATURE REQUEST] Concise description of the new feature'
labels: 'C-feature-request'
assignees: ''

---

<!-- Thank you for taking the time to suggest a feature for our operating system.
Please help us understand your proposal by filling out the information below. -->

### Feature Description

<!-- Clearly and concisely describe the feature you'd like to have added. What is it? How should it work? -->

### Problem or Need

<!-- If this feature addresses a specific problem or need you have encountered, describe it. Why is the feature important or beneficial to you and potentially other users? -->

### Suggested Implementation

<!-- If you have an idea of how this feature should be implemented, provide details here. This can include:

- Technical details, design considerations, or architecture diagrams
- Third-party libraries or services, if applicable
- Pseudo-code, API method names, or sample code snippets -->

### Possible Alternatives

<!-- If you've considered any alternative solutions or workarounds, please list those here. -->

### Additional Context and Screenshots

<!-- Provide any additional context that could help us understand the feature request better. Screenshots, mockups, and diagrams are also welcomed. -->

<!-- Again, we greatly appreciate your contribution to improving our operating system! -->

```

### Enhancement

```md
---
name: Enhancement Request
about: Suggest an enhancement for an existing feature of this operating system
title: '[ENHANCEMENT] Concise description of the enhancement'
labels: 'C-enhancement'
assignees: ''

---

<!-- Thank you for taking the time to suggest an enhancement for our operating system. Please provide a clear and concise description of the enhancement you want and the reasons why it would be beneficial. -->

### Current Feature

<!-- Describe the existing feature or behavior that you are proposing to enhance. Please be specific. -->

### Enhancement Description

<!-- Clearly and concisely describe the enhancement you are proposing. Explain how it should work in practice and what the expected benefits are. -->

### Motivation

<!-- Explain why this enhancement would be useful to most operating system users. Provide specific use cases, experiences, or issues with the current functionality that this enhancement would address. -->

### Possible Implementations

<!-- If you have ideas on how to implement this enhancement, please detail them here. This can include:

- Technical implementation details, design considerations, or architecture sketches
- Modifications to user interface, system behavior, or core functionality
- Code snippets, pseudo-code, or example scenarios -->

### Additional Context

<!-- Add any other context, mock-ups, sketches, screenshots, or examples that could help clarify the enhancement request. -->

<!-- We appreciate your initiative in proposing this enhancement and your help in making our operating system better! -->

```

### Documentation
```md
---
name: Documentation Request
about: Suggest improvements or additions to the documentation
title: '[DOC] Concise description of the documentation issue or suggestion'
labels: 'C-documentation'
assignees: ''

---

<!-- 
Thank you for contributing to our documentation! Documentation improvements help everyone better understand and use the operating system. Please provide us with clear and detailed information about the issue or suggestion.
-->

### Documentation Section

<!-- 
Please identify the section or page of the documentation where you are suggesting an improvement. Include a URL if possible.
-->

### Suggested Improvement

<!-- 
Clearly and concisely describe the improvement you are suggesting. Are you proposing corrections, additions, or modifications? Please be specific and provide as much detail as possible to explain your suggestion.
-->

### Motivation and Context

<!--
Why is this improvement important? Explain the context behind your documentation request. For example, did you find the current documentation unclear, lacking in detail, or incorrect? How will your suggestion improve the documentation?
-->

### Additional Information

<!--
Include any additional information, such as references to external documentation, screenshots, or examples, that will help clarify your suggestion.
-->

<!-- 
Your contributions to making our documentation more clear and comprehensive are greatly appreciated!
-->

```

### Question
```md
---
name: Question
about: Ask a question or seek clarification about Asterinas
title: '[QUESTION] Short summary of your question'
labels: 'C-question'
assignees: ''

---

<!-- Please ensure your question has not been answered in our documentation before submitting. Thank you for reaching out with your question! -->

### Your Question

<!-- Provide a clear and concise description of what you want to know or need clarification about. -->

### What You Have Tried

<!-- Let us know what you've tried to do to find an answer to your question. This can include documentation you've reviewed, search engines you've consulted, and so on. -->

### Relevant Documentation or Forum Link 

<!-- If there is a part of the documentation or a forum thread that's relevant to your question, please provide a link here. -->

### Additional context

<!-- Provide any other context or details that might be helpful for answering your question. -->

<!-- We appreciate your engagement and are happy to help you get the most out of our operating system! -->

```

### Tracking Issue
```md
---
name: Tracking Issue
about: Track the progress of a specific task or feature
title: '[TRACKING] Short summary of the task or feature'
labels: 'C-tracking-issue'

---
### Description
<!-- Provide a brief description of the task or feature being tracked！ -->

### Current Status

<!-- Describe the current status or progress of the task or feature -->

### Additional Information 
<!-- Add any other relevant information, links, or context related to the tracking issue -->

```
---

I would like to gather your input. Your feedback on this matter is greatly appreciated. Thank you!

**Comment by StevenJiang1110** [comment]
It may be better to have the following labels for PRs. These lables can be beneficial for automatically generating CHANGELOGS.

The definitions are from [keepchangelog](https://keepachangelog.com/en/1.0.0)

**Added**: for new features.
**Changed**: for changes in existing functionality.
**Deprecated**: for soon-to-be removed features.
**Removed**: for now removed features.
**Fixed**: for any bug fixes.
**Security**: in case of vulnerabilities.

As labels, they may be of differnet names.

**Comment by lrh2000** [comment]
> title: '[TRACKING] Short summary of the task or feature'

Do we need to repeat the label in the title?

> C-question: Ask questions related to the project
> 
> S-invalid: invalid question
> S-stale: Questions that no one has followed up on for a long time

Questions look special? Two out of four status labels are dedicated to questions?

Should we use GitHub issues for questions? We can use GitHub discussion / Zulip instead.

> S-stale: Questions that no one has followed up on for a long time

Will we automatically close stale issues?

> C-need-triage: issues cannot be recognized.

I think that this label should mean that the issue is new and has not been categorized.

> S-wontfix: Problems that will not be fixed

GitHub issues can be closed as "not planned", but we may still need such a label for other reasons. For example, one reason might be that this label can only be added by maintainers?

> O-dependency: PR related to dependency library update

Just curiosity, what does 'O' stand for?

**Comment by grief8** [comment]
Thank you for your reply @lrh2000 ! 

> > title: '[TRACKING] Short summary of the task or feature'
> 
> Do we need to repeat the label in the title?
- Repetition is not necessary. You can try https://github.com/grief8/asterinas/issues/new/choose .

> > C-question: Ask questions related to the project
> > S-invalid: invalid question
> > S-stale: Questions that no one has followed up on for a long time
> 
> Questions look special? Two out of four status labels are dedicated to questions?
- I will modify `S-invalid, S-stale`. It refers to issues.

> Should we use GitHub issues for questions? We can use GitHub discussion / Zulip instead.
- GitHub discussion and Zulip are better, I think. We can still reserve a `Question` template to guide contributors to the right links, e.g. [Rust](<https://github.com/rust-lang/rust/issues/new/choose>).

> > S-stale: Questions that no one has followed up on for a long time
> 
> Will we automatically close stale issues?
- We won't close `S-stale` ones. I think it can be used to remind maintainers to deal with it. 

> > C-need-triage: issues cannot be recognized.
> 
> I think that this label should mean that the issue is new and has not been categorized.
- Your statement is more accurate. `C-need-triage` will be linked with blank issue template, which is empty. 

> > S-wontfix: Problems that will not be fixed
> 
> GitHub issues can be closed as "not planned", but we may still need such a label for other reasons. For example, one reason might be that this label can only be added by maintainers?
You are right. It can only be added by maintainers.

> 
> > O-dependency: PR related to dependency library update
> 
> Just curiosity, what does 'O' stand for?

- It means objective/target-specific.

**Comment by grief8** [comment]
> It may be better to have the following labels for PRs. These lables can be beneficial for automatically generating CHANGELOGS.
> 
> The definitions are from [keepchangelog](https://keepachangelog.com/en/1.0.0)
> 
> **Added**: for new features. **Changed**: for changes in existing functionality. **Deprecated**: for soon-to-be removed features. **Removed**: for now removed features. **Fixed**: for any bug fixes. **Security**: in case of vulnerabilities.
> 
> As labels, they may be of differnet names.

Thanks for your feedback @StevenJiang1110 . These labels can be set up for pull requests. **Deprecated** should be controlled by maintainers. `Added=O-feature, Changed=O-refactor, Fixed=O-bugfix` can be substituted. `Security` may be added later.

**Comment by lrh2000** [comment]
> * Repetition is not necessary. You can try https://github.com/grief8/asterinas/issues/new/choose .

Well, this URL redirects to https://github.com/grief8/asterinas/issues/new and I see nothing but a text box. Is this expected?

**Comment by grief8** [comment]
> https://github.com/grief8/asterinas/issues/new

Sorry, I just discard the changes for rebasing the new commits. Now it can work. We just select the template and propose issues with labels.

**Comment by junyang-zh** [comment]
In bug issue template:

> ```
> ### Screenshots
>  
> ```

Maybe "log" is better? Non-plaintext discussions are hard to follow.

I am also wandering RFC issues, which is not covered in the issue type.

**Comment by grief8** [comment]
> In bug issue template:
> 
> > ```
> > ### Screenshots
> >  
> > ```
> 
> Maybe "log" is better? Non-plaintext discussions are hard to follow.
> 
> I am also wandering RFC issues, which is not covered in the issue type.

Log is better. 

I'm not sure that whether we should add `C-RFC`. Sometimes it may be overlapped with `C-feature-request` or `C-enhancement`. Is [RFC] in the title enough?
