### ISSUE TITLE
[TDX] Support qcow2 format in new osdk crate version.

### ISSUE THREAD

**Issue by Hsy-Intel** [asterinas/asterinas#922]
The current osdk crate in `crates.io` does not support the `qcow2` format, which is required by TDX. So we need to update the osdk crate in `crates.io`.

**Comment by tatetian** [comment]
@junyang-zh Could you publish the latest OSDK?

**Comment by junyang-zh** [comment]
> Could you publish the latest OSDK?

@tatetian That requires a new version number. If we don't bump the version of the main crate now I may use 0.4.3 for it.

**Comment by tatetian** [comment]
> > Could you publish the latest OSDK?
> 
> @tatetian That requires a new version number. If we don't bump the version of the main crate now I may use 0.4.3 for it.

Feel free to bump the version to `0.5.0`. We haven't bumped the version for some time. There has been tons of changes.

**Comment by junyang-zh** [comment]
pushed, closing
