### ISSUE TITLE
[Pre-RFC] Is UIO all we need?

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#930]
I am all new to I/O subsystems. This is just a wild thought.

We may consider making the majority of Asterinas driver development follow [the Linux UIO style](https://www.kernel.org/doc/html/v4.12/driver-api/uio-howto.html): a small (and even universal) kernel module, an arbitrary user space driver. We may even consider just literally copy Linux's interface of devfs (`/dev/uioX`), which would make Linux user space drivers (like DPDK) "just works".

**Comment by junyang-zh** [comment]
Seems not. If the user can just use system calls rather than user space libraries it would be slow since kernel need to interact with user space drivers when handling syscalls. This is slow.

But UIO still seems a good thing, rather than the only thing we need.

**Comment by tatetian** [comment]
UIO should be viewed as a complement, instead of a replacement, of kernel-based I/O.

**Comment by junyang-zh** [comment]
Postponed
