### ISSUE TITLE
[BUG] Error while running benchmark CI on TDX machine

### ISSUE THREAD

**Issue by grief8** [asterinas/asterinas#934]
## Description

I encountered the following error when I ran the benchmark CI on the TDX machine. The details are shown in [log].(https://github.com/grief8/asterinas/actions/runs/9494650338/job/26165399130)
```log
Error: : Cannot parse TOML file, missing field `features`. /__w/asterinas/asterinas/OSDK.toml:721..726:
 hod = "qemu-direct"
build.strip_elf = true
qe
make: *** [Makefile:139: build] Error 4
Error: Failed to parse benchmark results from regression/benchmark/output.txt
Error: Process completed with exit code 1.
```

This error only happens in CI. When I execute it manually, it works well.

---
@junyang-zh Could you please give me some input?

**Comment by junyang-zh** [comment]
I inspected your code and found no obvious problems. There might be one reason causing this failure: root `Makefile` don't install OSDK from source if `~/.cargo/bin/cargo-osdk` exists. In the image of your local hosted machine it may have an already installed earlier version.

Please try `make install_osdk` before `make run BENCHMARK=${benchmark} ENABLE_KVM=${enable_kvm} RELEASE=1 2>&1 | tee "${aster_output}"` in `benchmark.sh`.

**Comment by grief8** [comment]
> I inspected your code and found no obvious problems. There might be one reason causing this failure: root `Makefile` don't install OSDK from source if `~/.cargo/bin/cargo-osdk` exists. In the image of your local hosted machine it may have an already installed earlier version.
> 
> Please try `make install_osdk` before `make run BENCHMARK=${benchmark} ENABLE_KVM=${enable_kvm} RELEASE=1 2>&1 | tee "${aster_output}"` in `benchmark.sh`.

Thank you for your feedback! I will try it soon.

**Comment by grief8** [comment]
It just works!!! Thank you again for your help! @junyang-zh
