### ISSUE TITLE
[Typo] Some typo in `net/socket/mod.rs`

### ISSUE THREAD

**Issue by CherishCai** [asterinas/asterinas#940]
Are there any typos?

- L32 "listen() is not supported"
https://github.com/asterinas/asterinas/blob/6014ecfc0fb4c901f6abb5e4c9bed608b1fba640/kernel/aster-nix/src/net/socket/mod.rs#L30-L33

- L78 "sendto() is not supported"
https://github.com/asterinas/asterinas/blob/6014ecfc0fb4c901f6abb5e4c9bed608b1fba640/kernel/aster-nix/src/net/socket/mod.rs#L71-L79

**Comment by StevenJiang1110** [comment]
Thank you for your report!

Regarding both issues #939 and this issue, they are indeed problems that need to be addressed. Would you like to open a pull request to fix these issues? If not, I can take care of fixing them promptly.

**Comment by CherishCai** [comment]
It is my honor, I will submit a PR later

**Comment by CherishCai** [comment]
close with https://github.com/asterinas/asterinas/pull/942
