### ISSUE TITLE
[Performance] `fork` is too slow

### ISSUE THREAD

**Issue by skpupil** [asterinas/asterinas#963]
related to [issue](https://github.com/asterinas/asterinas/issues/889#issuecomment-2182371864).

When using `fork()`, the performance of asterinas is less than 5% of that of linux.

[spawn](https://github.com/kdlucas/byte-unixbench/blob/master/UnixBench/src/spawn.c)

**Comment by junyang-zh** [comment]
I have sampled 100 stack traces using GDB in release mode (KVM off) running the spawn benchmark. Here's the rendered flamegraph.

![kernel](https://github.com/asterinas/asterinas/assets/30975570/b30d7030-57b9-4a7f-b921-e9c0d5203b84)

**Comment by junyang-zh** [comment]
Here's the flame graph after #895, which solves the problem.

![kernel_vmspacerw](https://github.com/asterinas/asterinas/assets/30975570/070f815e-e6e6-4abe-b56a-13a76e36a271)
