### ISSUE TITLE
ktest as a kernel

### ISSUE THREAD

**Issue by junyang-zh** [asterinas/asterinas#975]
### Summary

Well, I want to make ktest as a kernel built on top of aster-frame (OSTD), and run as a kernel. Currently the ktest crate is a dependency of aster-frame, which leads to many problems such as:
 - a lot of runtime needed when running ktest, which need to be passed as parameters #834 ;
 - need to pass cfg to aster-frame when rebuilding the test #974 ;

By making ktest a kernel depending on aster-frame, which has it's entrypoint as `#[aster_main]` (`#[ostd::main]`), it works for all the above problems.

### Proposal

Originally the dependency chain of testing a target crate `A` is:

```text
ktest <---------------- ostd <--- A <--- base_crate
                       /         / 
ktest_proc_macro <----'---------'
```

The proposed one is:

```text

        .-- ktest <----(if testing)----.
        v                               \
  .-- ostd <---------- A <--------- base_crate
  v                   /
ktest_proc_macro <---'
```

Instead of a conditional compilation to choose the ktest entry point at `aster_frame::boot::call_aster_main`, the ktest entry point should be registered as **STRONG** `#[aster_main]`, while other kernel's `#[aster_main]` should be WEAK. So during linking, if the ktest main exist ktests will be excecuted, other wise kernel main would be executed.

**Comment by tatetian** [comment]
This proposal aims to address to problems.

> * a lot of runtime needed when running ktest, which need to be passed as parameters https://github.com/asterinas/asterinas/pull/834 ;
> * need to pass cfg to aster-frame when rebuilding the test https://github.com/asterinas/asterinas/issues/974 ;

I can see why this proposal is able to resolve the first problem. But why can it address the second?

**Comment by StevenJiang1110** [comment]
> The proposed one is:

```plain
        .-- ktest <----(if testing)----.
        v                               \
  .-- ostd <---------- A <--------- base_crate
  v                   /
ktest_proc_macro <---'
```

Users don't need to be aware of the existence of the `ktest_proc_macro` and `ktest` crates, correct? The `ktest` crate is solely a dependency of the `base_crate`, and the `ktest_proc_macro` is now re-exported from `ostd`. Therefore, the crate A to be tested can only depend on `ostd`.

**Comment by grief8** [comment]
Due to the current implementation of both `#[ostd::ktest]` and `ktest` relying on `KtestItem` and `KtestItemInfo`, we cannot directly move `ktest` above `ostd`.

The most naive implementation would be to move the logic for running `ktest` to the top level, creating a `ktest_run`. However, the definition of `KtestItem` would still need to be retained within `OSTD` to allow the use of `#[ostd::ktest]`. This approach would still leave `OSTD` partially dependent on `ktest`.

```text
		            .-- ktest_run <---(if testing)---.
		            v                                 \
  ktest_proc_macro <-----ostd <---------- A <------------- base_crate
               \	  v            
                .----->  ktest 
```

An alternative solution might be to place the parameters that originally needed to be wrapped in `KtestItem` into a `.ktest_array`, and then retrieve these parameters to generate `KtestItem` objects during execution. However, this might not be an elegant solution.

I haven't been able to think of a better approach☹️. Could you give me some input @junyang-zh ?

**Comment by junyang-zh** [comment]
> The most naive implementation would be to move the logic for running `ktest` to the top level, creating a `ktest_run`. However, the definition of `KtestItem` would still need to be retained within `OSTD` to allow the use of `#[ostd::ktest]`. This approach would still leave `OSTD` partially dependent on `ktest`.
> 
> ```
> 		            .-- ktest_run <---(if testing)---.
> 		            v                                 \
>   ktest_proc_macro <-----ostd <---------- A <------------- base_crate
>                \	  v            
>                 .----->  ktest 
> ```

Your question makes sense. And the best solution I can think of is just like yours, splitting the crate into two.

So it seems that we are just making the ktest runner a kernel. The ktest item definitions are still a dependency of OSTD.
