### ISSUE TITLE
Random PageFault in CI

### ISSUE THREAD

**Issue by cchanging** [asterinas/asterinas#977]
Currently The CI may encounter page fault error, which seems to be a random generated error that appears to have been caused by the recent merged PR.

https://github.com/asterinas/asterinas/actions/runs/9673150349/job/26686599567
https://github.com/asterinas/asterinas/actions/runs/9676228375/job/26695331329

![image](https://github.com/asterinas/asterinas/assets/33800552/973ed8ac-219f-4c54-9f9f-8c9906d68ab2)

**Comment by junyang-zh** [comment]
https://github.com/asterinas/asterinas/actions/runs/9680705184

This is tested at [a2060039c2671e335a832ac52653384e0d61e1d9](https://github.com/asterinas/asterinas/commit/a2060039c2671e335a832ac52653384e0d61e1d9). So commits after it should be exempted from introducing the bug.

It may relates to #868 , suggesting a long-undiscovered problem.

**Comment by lrh2000** [comment]
The minimal reproducible example should be:
```bash
while true; do
	/opt/syscall_test/tests/epoll_test --gtest_filter=EpollTest.UnblockWithSignal
done
```

It seems that his test contains races, so we'd better just disable it. See https://github.com/asterinas/asterinas/pull/1035.
